<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App"/>
	</ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4"/>
    <PackageReference Include="CommonServiceLocator" Version="2.0.6"/>
    <PackageReference Include="FluentNHibernate" Version="3.4.1"/>
    <PackageReference Include="NHibernate" Version="5.6.2"/>
    <PackageReference Include="Castle.Windsor" Version="6.0.0"/>
  </ItemGroup>

</Project>
