/*ALTER TABLE [dbo].[ApprovalsXSplits]
    ADD CONSTRAINT [PK_ApprovalsXSplits_1] PRIMARY KEY NONCLUSTERED ([ApprovalId] ASC, [SplitId] ASC) WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = OFF, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];*/

