ALTER TABLE [dbo].[OrderRequestSavesXAttachments]
    ADD CONSTRAINT [PK_OrderRequestSavesXAttachments] PRIMARY KEY CLUSTERED ([OrderRequestSaveId] ASC, [AttachmentId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

