ALTER TABLE [dbo].[Permissions]
    ADD CONSTRAINT [PK_Permissions] PRIMARY KEY CLUSTERED ([RoleId] ASC, [UserId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

