ALTER TABLE [dbo].[ParamNameAndValue]
    ADD CONSTRAINT [PK_TableName_1] PRIMARY KEY CLUSTERED ([ParamName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

