ALTER TABLE [dbo].[vVendorAddresses]
    ADD CONSTRAINT [PK_vVendorAddresses] PRIMARY KEY CLUSTERED ([VendorId] ASC, [TypeCode] ASC, [PartitionColumn] ASC) WITH (ALLOW_PAGE_LOCKS = OFF, ALLOW_ROW_LOCKS = OFF, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);



