ALTER TABLE [dbo].[vBuildings]
    ADD CONSTRAINT [PK_vBuildings] PRIMARY KEY CLUSTERED ([CampusCode] ASC, [BuildingCode] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

