#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrAdmin.Entities.LimitedSubmissions
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OVC_Dev")]
	public partial class LimitedSubmissionsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSponsor(Sponsor instance);
    partial void UpdateSponsor(Sponsor instance);
    partial void DeleteSponsor(Sponsor instance);
    partial void InsertAssignment(Assignment instance);
    partial void UpdateAssignment(Assignment instance);
    partial void DeleteAssignment(Assignment instance);
    partial void InsertDivision(Division instance);
    partial void UpdateDivision(Division instance);
    partial void DeleteDivision(Division instance);
    partial void InsertFundingAnnouncement(FundingAnnouncement instance);
    partial void UpdateFundingAnnouncement(FundingAnnouncement instance);
    partial void DeleteFundingAnnouncement(FundingAnnouncement instance);
    partial void InsertLimitedSubmission(LimitedSubmission instance);
    partial void UpdateLimitedSubmission(LimitedSubmission instance);
    partial void DeleteLimitedSubmission(LimitedSubmission instance);
    partial void InsertOtherBudgetCost(OtherBudgetCost instance);
    partial void UpdateOtherBudgetCost(OtherBudgetCost instance);
    partial void DeleteOtherBudgetCost(OtherBudgetCost instance);
    partial void InsertProgram(Program instance);
    partial void UpdateProgram(Program instance);
    partial void DeleteProgram(Program instance);
    partial void InsertApplication(Application instance);
    partial void UpdateApplication(Application instance);
    partial void DeleteApplication(Application instance);
    #endregion
		
		public LimitedSubmissionsDataContext() : 
				base(global::OrAdmin.Entities.Properties.Settings.Default.OVC_DevConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LimitedSubmissionsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LimitedSubmissionsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LimitedSubmissionsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LimitedSubmissionsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Sponsor> Sponsors
		{
			get
			{
				return this.GetTable<Sponsor>();
			}
		}
		
		public System.Data.Linq.Table<Assignment> Assignments
		{
			get
			{
				return this.GetTable<Assignment>();
			}
		}
		
		public System.Data.Linq.Table<Division> Divisions
		{
			get
			{
				return this.GetTable<Division>();
			}
		}
		
		public System.Data.Linq.Table<FundingAnnouncement> FundingAnnouncements
		{
			get
			{
				return this.GetTable<FundingAnnouncement>();
			}
		}
		
		public System.Data.Linq.Table<LimitedSubmission> LimitedSubmissions
		{
			get
			{
				return this.GetTable<LimitedSubmission>();
			}
		}
		
		public System.Data.Linq.Table<OtherBudgetCost> OtherBudgetCosts
		{
			get
			{
				return this.GetTable<OtherBudgetCost>();
			}
		}
		
		public System.Data.Linq.Table<Program> Programs
		{
			get
			{
				return this.GetTable<Program>();
			}
		}
		
		public System.Data.Linq.Table<Application> Applications
		{
			get
			{
				return this.GetTable<Application>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LTD_Sponsors")]
	public partial class Sponsor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _SponsorName;
		
		private string _SponsorContact;
		
		private string _Notes;
		
		private string _SponsorLink;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private string _AddedBy;
		
		private bool _LegacyMsAccessData;
		
		private EntitySet<Program> _Programs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSponsorNameChanging(string value);
    partial void OnSponsorNameChanged();
    partial void OnSponsorContactChanging(string value);
    partial void OnSponsorContactChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnSponsorLinkChanging(string value);
    partial void OnSponsorLinkChanged();
    partial void OnAddedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnAddedOnChanged();
    partial void OnAddedByChanging(string value);
    partial void OnAddedByChanged();
    partial void OnLegacyMsAccessDataChanging(bool value);
    partial void OnLegacyMsAccessDataChanged();
    #endregion
		
		public Sponsor()
		{
			this._Programs = new EntitySet<Program>(new Action<Program>(this.attach_Programs), new Action<Program>(this.detach_Programs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SponsorName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string SponsorName
		{
			get
			{
				return this._SponsorName;
			}
			set
			{
				if ((this._SponsorName != value))
				{
					this.OnSponsorNameChanging(value);
					this.SendPropertyChanging();
					this._SponsorName = value;
					this.SendPropertyChanged("SponsorName");
					this.OnSponsorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SponsorContact", DbType="NVarChar(MAX)")]
		public string SponsorContact
		{
			get
			{
				return this._SponsorContact;
			}
			set
			{
				if ((this._SponsorContact != value))
				{
					this.OnSponsorContactChanging(value);
					this.SendPropertyChanging();
					this._SponsorContact = value;
					this.SendPropertyChanged("SponsorContact");
					this.OnSponsorContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SponsorLink", DbType="NVarChar(256)")]
		public string SponsorLink
		{
			get
			{
				return this._SponsorLink;
			}
			set
			{
				if ((this._SponsorLink != value))
				{
					this.OnSponsorLinkChanging(value);
					this.SendPropertyChanging();
					this._SponsorLink = value;
					this.SendPropertyChanged("SponsorLink");
					this.OnSponsorLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this.OnAddedOnChanging(value);
					this.SendPropertyChanging();
					this._AddedOn = value;
					this.SendPropertyChanged("AddedOn");
					this.OnAddedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedBy", DbType="NVarChar(64)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this.OnAddedByChanging(value);
					this.SendPropertyChanging();
					this._AddedBy = value;
					this.SendPropertyChanged("AddedBy");
					this.OnAddedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegacyMsAccessData", DbType="Bit NOT NULL")]
		public bool LegacyMsAccessData
		{
			get
			{
				return this._LegacyMsAccessData;
			}
			set
			{
				if ((this._LegacyMsAccessData != value))
				{
					this.OnLegacyMsAccessDataChanging(value);
					this.SendPropertyChanging();
					this._LegacyMsAccessData = value;
					this.SendPropertyChanged("LegacyMsAccessData");
					this.OnLegacyMsAccessDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sponsor_Program", Storage="_Programs", ThisKey="Id", OtherKey="SponsorId")]
		public EntitySet<Program> Programs
		{
			get
			{
				return this._Programs;
			}
			set
			{
				this._Programs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Programs(Program entity)
		{
			this.SendPropertyChanging();
			entity.Sponsor = this;
		}
		
		private void detach_Programs(Program entity)
		{
			this.SendPropertyChanging();
			entity.Sponsor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LTD_Assignments")]
	public partial class Assignment : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _LimitedSubmissionId;
		
		private string _AssignedToUserKerberos;
		
		private System.Nullable<System.DateTime> _AssignedOn;
		
		private string _AssignedBy;
		
		private bool _LegacyMsAccessData;
		
		private EntityRef<LimitedSubmission> _LimitedSubmission;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLimitedSubmissionIdChanging(int value);
    partial void OnLimitedSubmissionIdChanged();
    partial void OnAssignedToUserKerberosChanging(string value);
    partial void OnAssignedToUserKerberosChanged();
    partial void OnAssignedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnAssignedOnChanged();
    partial void OnAssignedByChanging(string value);
    partial void OnAssignedByChanged();
    partial void OnLegacyMsAccessDataChanging(bool value);
    partial void OnLegacyMsAccessDataChanged();
    #endregion
		
		public Assignment()
		{
			this._LimitedSubmission = default(EntityRef<LimitedSubmission>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LimitedSubmissionId", DbType="Int NOT NULL")]
		public int LimitedSubmissionId
		{
			get
			{
				return this._LimitedSubmissionId;
			}
			set
			{
				if ((this._LimitedSubmissionId != value))
				{
					if (this._LimitedSubmission.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLimitedSubmissionIdChanging(value);
					this.SendPropertyChanging();
					this._LimitedSubmissionId = value;
					this.SendPropertyChanged("LimitedSubmissionId");
					this.OnLimitedSubmissionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignedToUserKerberos", DbType="NVarChar(64)")]
		public string AssignedToUserKerberos
		{
			get
			{
				return this._AssignedToUserKerberos;
			}
			set
			{
				if ((this._AssignedToUserKerberos != value))
				{
					this.OnAssignedToUserKerberosChanging(value);
					this.SendPropertyChanging();
					this._AssignedToUserKerberos = value;
					this.SendPropertyChanged("AssignedToUserKerberos");
					this.OnAssignedToUserKerberosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AssignedOn
		{
			get
			{
				return this._AssignedOn;
			}
			set
			{
				if ((this._AssignedOn != value))
				{
					this.OnAssignedOnChanging(value);
					this.SendPropertyChanging();
					this._AssignedOn = value;
					this.SendPropertyChanged("AssignedOn");
					this.OnAssignedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignedBy", DbType="NVarChar(64)")]
		public string AssignedBy
		{
			get
			{
				return this._AssignedBy;
			}
			set
			{
				if ((this._AssignedBy != value))
				{
					this.OnAssignedByChanging(value);
					this.SendPropertyChanging();
					this._AssignedBy = value;
					this.SendPropertyChanged("AssignedBy");
					this.OnAssignedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegacyMsAccessData", DbType="Bit NOT NULL")]
		public bool LegacyMsAccessData
		{
			get
			{
				return this._LegacyMsAccessData;
			}
			set
			{
				if ((this._LegacyMsAccessData != value))
				{
					this.OnLegacyMsAccessDataChanging(value);
					this.SendPropertyChanging();
					this._LegacyMsAccessData = value;
					this.SendPropertyChanged("LegacyMsAccessData");
					this.OnLegacyMsAccessDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LimitedSubmission_Assignment", Storage="_LimitedSubmission", ThisKey="LimitedSubmissionId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public LimitedSubmission LimitedSubmission
		{
			get
			{
				return this._LimitedSubmission.Entity;
			}
			set
			{
				LimitedSubmission previousValue = this._LimitedSubmission.Entity;
				if (((previousValue != value) 
							|| (this._LimitedSubmission.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LimitedSubmission.Entity = null;
						previousValue.Assignments.Remove(this);
					}
					this._LimitedSubmission.Entity = value;
					if ((value != null))
					{
						value.Assignments.Add(this);
						this._LimitedSubmissionId = value.Id;
					}
					else
					{
						this._LimitedSubmissionId = default(int);
					}
					this.SendPropertyChanged("LimitedSubmission");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LTD_Divisions")]
	public partial class Division : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _DivisionAbbrv;
		
		private string _DivisionName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDivisionAbbrvChanging(string value);
    partial void OnDivisionAbbrvChanged();
    partial void OnDivisionNameChanging(string value);
    partial void OnDivisionNameChanged();
    #endregion
		
		public Division()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionAbbrv", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string DivisionAbbrv
		{
			get
			{
				return this._DivisionAbbrv;
			}
			set
			{
				if ((this._DivisionAbbrv != value))
				{
					this.OnDivisionAbbrvChanging(value);
					this.SendPropertyChanging();
					this._DivisionAbbrv = value;
					this.SendPropertyChanged("DivisionAbbrv");
					this.OnDivisionAbbrvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string DivisionName
		{
			get
			{
				return this._DivisionName;
			}
			set
			{
				if ((this._DivisionName != value))
				{
					this.OnDivisionNameChanging(value);
					this.SendPropertyChanging();
					this._DivisionName = value;
					this.SendPropertyChanged("DivisionName");
					this.OnDivisionNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LTD_FundingAnnouncements")]
	public partial class FundingAnnouncement : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Title;
		
		private string _SponsorName;
		
		private string _SponsorDueDate;
		
		private string _FundingArea;
		
		private string _Link;
		
		private string _BudgetLimit;
		
		private bool _IsHumanities;
		
		private System.Nullable<System.DateTime> _PostedOn;
		
		private string _PostedBy;
		
		private bool _LegacyMsAccessData;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnSponsorNameChanging(string value);
    partial void OnSponsorNameChanged();
    partial void OnSponsorDueDateChanging(string value);
    partial void OnSponsorDueDateChanged();
    partial void OnFundingAreaChanging(string value);
    partial void OnFundingAreaChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnBudgetLimitChanging(string value);
    partial void OnBudgetLimitChanged();
    partial void OnIsHumanitiesChanging(bool value);
    partial void OnIsHumanitiesChanged();
    partial void OnPostedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnPostedOnChanged();
    partial void OnPostedByChanging(string value);
    partial void OnPostedByChanged();
    partial void OnLegacyMsAccessDataChanging(bool value);
    partial void OnLegacyMsAccessDataChanged();
    #endregion
		
		public FundingAnnouncement()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(512)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SponsorName", DbType="NVarChar(512)")]
		public string SponsorName
		{
			get
			{
				return this._SponsorName;
			}
			set
			{
				if ((this._SponsorName != value))
				{
					this.OnSponsorNameChanging(value);
					this.SendPropertyChanging();
					this._SponsorName = value;
					this.SendPropertyChanged("SponsorName");
					this.OnSponsorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SponsorDueDate", DbType="NVarChar(256)")]
		public string SponsorDueDate
		{
			get
			{
				return this._SponsorDueDate;
			}
			set
			{
				if ((this._SponsorDueDate != value))
				{
					this.OnSponsorDueDateChanging(value);
					this.SendPropertyChanging();
					this._SponsorDueDate = value;
					this.SendPropertyChanged("SponsorDueDate");
					this.OnSponsorDueDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FundingArea", DbType="NVarChar(256)")]
		public string FundingArea
		{
			get
			{
				return this._FundingArea;
			}
			set
			{
				if ((this._FundingArea != value))
				{
					this.OnFundingAreaChanging(value);
					this.SendPropertyChanging();
					this._FundingArea = value;
					this.SendPropertyChanged("FundingArea");
					this.OnFundingAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(256)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetLimit", DbType="NVarChar(256)")]
		public string BudgetLimit
		{
			get
			{
				return this._BudgetLimit;
			}
			set
			{
				if ((this._BudgetLimit != value))
				{
					this.OnBudgetLimitChanging(value);
					this.SendPropertyChanging();
					this._BudgetLimit = value;
					this.SendPropertyChanged("BudgetLimit");
					this.OnBudgetLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHumanities", DbType="Bit NOT NULL")]
		public bool IsHumanities
		{
			get
			{
				return this._IsHumanities;
			}
			set
			{
				if ((this._IsHumanities != value))
				{
					this.OnIsHumanitiesChanging(value);
					this.SendPropertyChanging();
					this._IsHumanities = value;
					this.SendPropertyChanged("IsHumanities");
					this.OnIsHumanitiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> PostedOn
		{
			get
			{
				return this._PostedOn;
			}
			set
			{
				if ((this._PostedOn != value))
				{
					this.OnPostedOnChanging(value);
					this.SendPropertyChanging();
					this._PostedOn = value;
					this.SendPropertyChanged("PostedOn");
					this.OnPostedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostedBy", DbType="NVarChar(64)")]
		public string PostedBy
		{
			get
			{
				return this._PostedBy;
			}
			set
			{
				if ((this._PostedBy != value))
				{
					this.OnPostedByChanging(value);
					this.SendPropertyChanging();
					this._PostedBy = value;
					this.SendPropertyChanged("PostedBy");
					this.OnPostedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegacyMsAccessData", DbType="Bit NOT NULL")]
		public bool LegacyMsAccessData
		{
			get
			{
				return this._LegacyMsAccessData;
			}
			set
			{
				if ((this._LegacyMsAccessData != value))
				{
					this.OnLegacyMsAccessDataChanging(value);
					this.SendPropertyChanging();
					this._LegacyMsAccessData = value;
					this.SendPropertyChanged("LegacyMsAccessData");
					this.OnLegacyMsAccessDataChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LTD_LimitedSubmissions")]
	public partial class LimitedSubmission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _AnnouncementNumber;
		
		private int _ProgramId;
		
		private System.Nullable<System.DateTime> _InternalDeadline;
		
		private System.Nullable<System.DateTime> _SponsorDeadline;
		
		private bool _MrakNominationLetter;
		
		private string _AllowableApplications;
		
		private int _PreproposalsReceivedCount;
		
		private string _Status;
		
		private int _NominationsCount;
		
		private string _NotificationStatus;
		
		private string _BudgetLimit;
		
		private string _Eligibility;
		
		private string _Notes;
		
		private string _RfaLink;
		
		private System.Nullable<System.DateTime> _DatePosted;
		
		private string _ProjectDuration;
		
		private string _LoiDueDate;
		
		private System.Nullable<System.DateTime> _LoiDate;
		
		private bool _LoiRequired;
		
		private string _FundingAreas;
		
		private string _EmailFundingArea;
		
		private string _EmailEligibility;
		
		private System.Nullable<System.DateTime> _SortDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private bool _IsHumanities;
		
		private string _SpotsOpen;
		
		private string _MemoTitle;
		
		private bool _Expand;
		
		private System.Nullable<System.DateTime> _SubmittedOn;
		
		private string _SubmittedBy;
		
		private bool _LegacyMsAccessData;
		
		private EntitySet<Assignment> _Assignments;
		
		private EntitySet<Application> _Applications;
		
		private EntityRef<Program> _Program;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAnnouncementNumberChanging(string value);
    partial void OnAnnouncementNumberChanged();
    partial void OnProgramIdChanging(int value);
    partial void OnProgramIdChanged();
    partial void OnInternalDeadlineChanging(System.Nullable<System.DateTime> value);
    partial void OnInternalDeadlineChanged();
    partial void OnSponsorDeadlineChanging(System.Nullable<System.DateTime> value);
    partial void OnSponsorDeadlineChanged();
    partial void OnMrakNominationLetterChanging(bool value);
    partial void OnMrakNominationLetterChanged();
    partial void OnAllowableApplicationsChanging(string value);
    partial void OnAllowableApplicationsChanged();
    partial void OnPreproposalsReceivedCountChanging(int value);
    partial void OnPreproposalsReceivedCountChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnNominationsCountChanging(int value);
    partial void OnNominationsCountChanged();
    partial void OnNotificationStatusChanging(string value);
    partial void OnNotificationStatusChanged();
    partial void OnBudgetLimitChanging(string value);
    partial void OnBudgetLimitChanged();
    partial void OnEligibilityChanging(string value);
    partial void OnEligibilityChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnRfaLinkChanging(string value);
    partial void OnRfaLinkChanged();
    partial void OnDatePostedChanging(System.Nullable<System.DateTime> value);
    partial void OnDatePostedChanged();
    partial void OnProjectDurationChanging(string value);
    partial void OnProjectDurationChanged();
    partial void OnLoiDueDateChanging(string value);
    partial void OnLoiDueDateChanged();
    partial void OnLoiDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLoiDateChanged();
    partial void OnLoiRequiredChanging(bool value);
    partial void OnLoiRequiredChanged();
    partial void OnFundingAreasChanging(string value);
    partial void OnFundingAreasChanged();
    partial void OnEmailFundingAreaChanging(string value);
    partial void OnEmailFundingAreaChanged();
    partial void OnEmailEligibilityChanging(string value);
    partial void OnEmailEligibilityChanged();
    partial void OnSortDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSortDateChanged();
    partial void OnEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEndDateChanged();
    partial void OnIsHumanitiesChanging(bool value);
    partial void OnIsHumanitiesChanged();
    partial void OnSpotsOpenChanging(string value);
    partial void OnSpotsOpenChanged();
    partial void OnMemoTitleChanging(string value);
    partial void OnMemoTitleChanged();
    partial void OnExpandChanging(bool value);
    partial void OnExpandChanged();
    partial void OnSubmittedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnSubmittedOnChanged();
    partial void OnSubmittedByChanging(string value);
    partial void OnSubmittedByChanged();
    partial void OnLegacyMsAccessDataChanging(bool value);
    partial void OnLegacyMsAccessDataChanged();
    #endregion
		
		public LimitedSubmission()
		{
			this._Assignments = new EntitySet<Assignment>(new Action<Assignment>(this.attach_Assignments), new Action<Assignment>(this.detach_Assignments));
			this._Applications = new EntitySet<Application>(new Action<Application>(this.attach_Applications), new Action<Application>(this.detach_Applications));
			this._Program = default(EntityRef<Program>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnnouncementNumber", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string AnnouncementNumber
		{
			get
			{
				return this._AnnouncementNumber;
			}
			set
			{
				if ((this._AnnouncementNumber != value))
				{
					this.OnAnnouncementNumberChanging(value);
					this.SendPropertyChanging();
					this._AnnouncementNumber = value;
					this.SendPropertyChanged("AnnouncementNumber");
					this.OnAnnouncementNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramId", DbType="Int NOT NULL")]
		public int ProgramId
		{
			get
			{
				return this._ProgramId;
			}
			set
			{
				if ((this._ProgramId != value))
				{
					if (this._Program.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProgramIdChanging(value);
					this.SendPropertyChanging();
					this._ProgramId = value;
					this.SendPropertyChanged("ProgramId");
					this.OnProgramIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InternalDeadline", DbType="DateTime")]
		public System.Nullable<System.DateTime> InternalDeadline
		{
			get
			{
				return this._InternalDeadline;
			}
			set
			{
				if ((this._InternalDeadline != value))
				{
					this.OnInternalDeadlineChanging(value);
					this.SendPropertyChanging();
					this._InternalDeadline = value;
					this.SendPropertyChanged("InternalDeadline");
					this.OnInternalDeadlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SponsorDeadline", DbType="DateTime")]
		public System.Nullable<System.DateTime> SponsorDeadline
		{
			get
			{
				return this._SponsorDeadline;
			}
			set
			{
				if ((this._SponsorDeadline != value))
				{
					this.OnSponsorDeadlineChanging(value);
					this.SendPropertyChanging();
					this._SponsorDeadline = value;
					this.SendPropertyChanged("SponsorDeadline");
					this.OnSponsorDeadlineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MrakNominationLetter", DbType="Bit NOT NULL")]
		public bool MrakNominationLetter
		{
			get
			{
				return this._MrakNominationLetter;
			}
			set
			{
				if ((this._MrakNominationLetter != value))
				{
					this.OnMrakNominationLetterChanging(value);
					this.SendPropertyChanging();
					this._MrakNominationLetter = value;
					this.SendPropertyChanged("MrakNominationLetter");
					this.OnMrakNominationLetterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowableApplications", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string AllowableApplications
		{
			get
			{
				return this._AllowableApplications;
			}
			set
			{
				if ((this._AllowableApplications != value))
				{
					this.OnAllowableApplicationsChanging(value);
					this.SendPropertyChanging();
					this._AllowableApplications = value;
					this.SendPropertyChanged("AllowableApplications");
					this.OnAllowableApplicationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreproposalsReceivedCount", DbType="Int NOT NULL")]
		public int PreproposalsReceivedCount
		{
			get
			{
				return this._PreproposalsReceivedCount;
			}
			set
			{
				if ((this._PreproposalsReceivedCount != value))
				{
					this.OnPreproposalsReceivedCountChanging(value);
					this.SendPropertyChanging();
					this._PreproposalsReceivedCount = value;
					this.SendPropertyChanged("PreproposalsReceivedCount");
					this.OnPreproposalsReceivedCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NominationsCount", DbType="Int NOT NULL")]
		public int NominationsCount
		{
			get
			{
				return this._NominationsCount;
			}
			set
			{
				if ((this._NominationsCount != value))
				{
					this.OnNominationsCountChanging(value);
					this.SendPropertyChanging();
					this._NominationsCount = value;
					this.SendPropertyChanged("NominationsCount");
					this.OnNominationsCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotificationStatus", DbType="NVarChar(256)")]
		public string NotificationStatus
		{
			get
			{
				return this._NotificationStatus;
			}
			set
			{
				if ((this._NotificationStatus != value))
				{
					this.OnNotificationStatusChanging(value);
					this.SendPropertyChanging();
					this._NotificationStatus = value;
					this.SendPropertyChanged("NotificationStatus");
					this.OnNotificationStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetLimit", DbType="NVarChar(512)")]
		public string BudgetLimit
		{
			get
			{
				return this._BudgetLimit;
			}
			set
			{
				if ((this._BudgetLimit != value))
				{
					this.OnBudgetLimitChanging(value);
					this.SendPropertyChanging();
					this._BudgetLimit = value;
					this.SendPropertyChanged("BudgetLimit");
					this.OnBudgetLimitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Eligibility", DbType="NVarChar(MAX)")]
		public string Eligibility
		{
			get
			{
				return this._Eligibility;
			}
			set
			{
				if ((this._Eligibility != value))
				{
					this.OnEligibilityChanging(value);
					this.SendPropertyChanging();
					this._Eligibility = value;
					this.SendPropertyChanged("Eligibility");
					this.OnEligibilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RfaLink", DbType="NVarChar(255)")]
		public string RfaLink
		{
			get
			{
				return this._RfaLink;
			}
			set
			{
				if ((this._RfaLink != value))
				{
					this.OnRfaLinkChanging(value);
					this.SendPropertyChanging();
					this._RfaLink = value;
					this.SendPropertyChanged("RfaLink");
					this.OnRfaLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatePosted", DbType="DateTime")]
		public System.Nullable<System.DateTime> DatePosted
		{
			get
			{
				return this._DatePosted;
			}
			set
			{
				if ((this._DatePosted != value))
				{
					this.OnDatePostedChanging(value);
					this.SendPropertyChanging();
					this._DatePosted = value;
					this.SendPropertyChanged("DatePosted");
					this.OnDatePostedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectDuration", DbType="NVarChar(256)")]
		public string ProjectDuration
		{
			get
			{
				return this._ProjectDuration;
			}
			set
			{
				if ((this._ProjectDuration != value))
				{
					this.OnProjectDurationChanging(value);
					this.SendPropertyChanging();
					this._ProjectDuration = value;
					this.SendPropertyChanged("ProjectDuration");
					this.OnProjectDurationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoiDueDate", DbType="NVarChar(255)")]
		public string LoiDueDate
		{
			get
			{
				return this._LoiDueDate;
			}
			set
			{
				if ((this._LoiDueDate != value))
				{
					this.OnLoiDueDateChanging(value);
					this.SendPropertyChanging();
					this._LoiDueDate = value;
					this.SendPropertyChanged("LoiDueDate");
					this.OnLoiDueDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoiDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LoiDate
		{
			get
			{
				return this._LoiDate;
			}
			set
			{
				if ((this._LoiDate != value))
				{
					this.OnLoiDateChanging(value);
					this.SendPropertyChanging();
					this._LoiDate = value;
					this.SendPropertyChanged("LoiDate");
					this.OnLoiDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoiRequired", DbType="Bit NOT NULL")]
		public bool LoiRequired
		{
			get
			{
				return this._LoiRequired;
			}
			set
			{
				if ((this._LoiRequired != value))
				{
					this.OnLoiRequiredChanging(value);
					this.SendPropertyChanging();
					this._LoiRequired = value;
					this.SendPropertyChanged("LoiRequired");
					this.OnLoiRequiredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FundingAreas", DbType="NVarChar(MAX)")]
		public string FundingAreas
		{
			get
			{
				return this._FundingAreas;
			}
			set
			{
				if ((this._FundingAreas != value))
				{
					this.OnFundingAreasChanging(value);
					this.SendPropertyChanging();
					this._FundingAreas = value;
					this.SendPropertyChanged("FundingAreas");
					this.OnFundingAreasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailFundingArea", DbType="NVarChar(MAX)")]
		public string EmailFundingArea
		{
			get
			{
				return this._EmailFundingArea;
			}
			set
			{
				if ((this._EmailFundingArea != value))
				{
					this.OnEmailFundingAreaChanging(value);
					this.SendPropertyChanging();
					this._EmailFundingArea = value;
					this.SendPropertyChanged("EmailFundingArea");
					this.OnEmailFundingAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailEligibility", DbType="NVarChar(MAX)")]
		public string EmailEligibility
		{
			get
			{
				return this._EmailEligibility;
			}
			set
			{
				if ((this._EmailEligibility != value))
				{
					this.OnEmailEligibilityChanging(value);
					this.SendPropertyChanging();
					this._EmailEligibility = value;
					this.SendPropertyChanged("EmailEligibility");
					this.OnEmailEligibilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SortDate
		{
			get
			{
				return this._SortDate;
			}
			set
			{
				if ((this._SortDate != value))
				{
					this.OnSortDateChanging(value);
					this.SendPropertyChanging();
					this._SortDate = value;
					this.SendPropertyChanged("SortDate");
					this.OnSortDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHumanities", DbType="Bit NOT NULL")]
		public bool IsHumanities
		{
			get
			{
				return this._IsHumanities;
			}
			set
			{
				if ((this._IsHumanities != value))
				{
					this.OnIsHumanitiesChanging(value);
					this.SendPropertyChanging();
					this._IsHumanities = value;
					this.SendPropertyChanged("IsHumanities");
					this.OnIsHumanitiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpotsOpen", DbType="NVarChar(256)")]
		public string SpotsOpen
		{
			get
			{
				return this._SpotsOpen;
			}
			set
			{
				if ((this._SpotsOpen != value))
				{
					this.OnSpotsOpenChanging(value);
					this.SendPropertyChanging();
					this._SpotsOpen = value;
					this.SendPropertyChanged("SpotsOpen");
					this.OnSpotsOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemoTitle", DbType="NVarChar(512)")]
		public string MemoTitle
		{
			get
			{
				return this._MemoTitle;
			}
			set
			{
				if ((this._MemoTitle != value))
				{
					this.OnMemoTitleChanging(value);
					this.SendPropertyChanging();
					this._MemoTitle = value;
					this.SendPropertyChanged("MemoTitle");
					this.OnMemoTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expand", DbType="Bit NOT NULL")]
		public bool Expand
		{
			get
			{
				return this._Expand;
			}
			set
			{
				if ((this._Expand != value))
				{
					this.OnExpandChanging(value);
					this.SendPropertyChanging();
					this._Expand = value;
					this.SendPropertyChanged("Expand");
					this.OnExpandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> SubmittedOn
		{
			get
			{
				return this._SubmittedOn;
			}
			set
			{
				if ((this._SubmittedOn != value))
				{
					this.OnSubmittedOnChanging(value);
					this.SendPropertyChanging();
					this._SubmittedOn = value;
					this.SendPropertyChanged("SubmittedOn");
					this.OnSubmittedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmittedBy", DbType="NVarChar(64)")]
		public string SubmittedBy
		{
			get
			{
				return this._SubmittedBy;
			}
			set
			{
				if ((this._SubmittedBy != value))
				{
					this.OnSubmittedByChanging(value);
					this.SendPropertyChanging();
					this._SubmittedBy = value;
					this.SendPropertyChanged("SubmittedBy");
					this.OnSubmittedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegacyMsAccessData", DbType="Bit NOT NULL")]
		public bool LegacyMsAccessData
		{
			get
			{
				return this._LegacyMsAccessData;
			}
			set
			{
				if ((this._LegacyMsAccessData != value))
				{
					this.OnLegacyMsAccessDataChanging(value);
					this.SendPropertyChanging();
					this._LegacyMsAccessData = value;
					this.SendPropertyChanged("LegacyMsAccessData");
					this.OnLegacyMsAccessDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LimitedSubmission_Assignment", Storage="_Assignments", ThisKey="Id", OtherKey="LimitedSubmissionId")]
		public EntitySet<Assignment> Assignments
		{
			get
			{
				return this._Assignments;
			}
			set
			{
				this._Assignments.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LimitedSubmission_LTD_Application", Storage="_Applications", ThisKey="Id", OtherKey="LimitedSubmissionId")]
		public EntitySet<Application> Applications
		{
			get
			{
				return this._Applications;
			}
			set
			{
				this._Applications.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Program_LimitedSubmission", Storage="_Program", ThisKey="ProgramId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Program Program
		{
			get
			{
				return this._Program.Entity;
			}
			set
			{
				Program previousValue = this._Program.Entity;
				if (((previousValue != value) 
							|| (this._Program.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Program.Entity = null;
						previousValue.LimitedSubmissions.Remove(this);
					}
					this._Program.Entity = value;
					if ((value != null))
					{
						value.LimitedSubmissions.Add(this);
						this._ProgramId = value.Id;
					}
					else
					{
						this._ProgramId = default(int);
					}
					this.SendPropertyChanged("Program");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Assignments(Assignment entity)
		{
			this.SendPropertyChanging();
			entity.LimitedSubmission = this;
		}
		
		private void detach_Assignments(Assignment entity)
		{
			this.SendPropertyChanging();
			entity.LimitedSubmission = null;
		}
		
		private void attach_Applications(Application entity)
		{
			this.SendPropertyChanging();
			entity.LimitedSubmission = this;
		}
		
		private void detach_Applications(Application entity)
		{
			this.SendPropertyChanging();
			entity.LimitedSubmission = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LTD_OtherBudgetCosts")]
	public partial class OtherBudgetCost : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _LimitedSubmissionId;
		
		private int _FormSection;
		
		private string _Description;
		
		private decimal _Cost;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLimitedSubmissionIdChanging(int value);
    partial void OnLimitedSubmissionIdChanged();
    partial void OnFormSectionChanging(int value);
    partial void OnFormSectionChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnCostChanging(decimal value);
    partial void OnCostChanged();
    #endregion
		
		public OtherBudgetCost()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LimitedSubmissionId", DbType="Int NOT NULL")]
		public int LimitedSubmissionId
		{
			get
			{
				return this._LimitedSubmissionId;
			}
			set
			{
				if ((this._LimitedSubmissionId != value))
				{
					this.OnLimitedSubmissionIdChanging(value);
					this.SendPropertyChanging();
					this._LimitedSubmissionId = value;
					this.SendPropertyChanged("LimitedSubmissionId");
					this.OnLimitedSubmissionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormSection", DbType="Int NOT NULL")]
		public int FormSection
		{
			get
			{
				return this._FormSection;
			}
			set
			{
				if ((this._FormSection != value))
				{
					this.OnFormSectionChanging(value);
					this.SendPropertyChanging();
					this._FormSection = value;
					this.SendPropertyChanged("FormSection");
					this.OnFormSectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Money NOT NULL")]
		public decimal Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this.OnCostChanging(value);
					this.SendPropertyChanging();
					this._Cost = value;
					this.SendPropertyChanged("Cost");
					this.OnCostChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LTD_Programs")]
	public partial class Program : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _SponsorId;
		
		private string _ProgramName;
		
		private string _Contact;
		
		private string _Link;
		
		private string _Cycle1Post;
		
		private string _Cycle2Post;
		
		private string _Cycle3Post;
		
		private string _Cycle1Due;
		
		private string _Cycle2Due;
		
		private string _Cycle3Due;
		
		private System.Nullable<int> _PostStatus;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private string _AddedBy;
		
		private string _Notes;
		
		private bool _LegacyMsAccessData;
		
		private EntitySet<LimitedSubmission> _LimitedSubmissions;
		
		private EntityRef<Sponsor> _Sponsor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSponsorIdChanging(int value);
    partial void OnSponsorIdChanged();
    partial void OnProgramNameChanging(string value);
    partial void OnProgramNameChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnCycle1PostChanging(string value);
    partial void OnCycle1PostChanged();
    partial void OnCycle2PostChanging(string value);
    partial void OnCycle2PostChanged();
    partial void OnCycle3PostChanging(string value);
    partial void OnCycle3PostChanged();
    partial void OnCycle1DueChanging(string value);
    partial void OnCycle1DueChanged();
    partial void OnCycle2DueChanging(string value);
    partial void OnCycle2DueChanged();
    partial void OnCycle3DueChanging(string value);
    partial void OnCycle3DueChanged();
    partial void OnPostStatusChanging(System.Nullable<int> value);
    partial void OnPostStatusChanged();
    partial void OnAddedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnAddedOnChanged();
    partial void OnAddedByChanging(string value);
    partial void OnAddedByChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnLegacyMsAccessDataChanging(bool value);
    partial void OnLegacyMsAccessDataChanged();
    #endregion
		
		public Program()
		{
			this._LimitedSubmissions = new EntitySet<LimitedSubmission>(new Action<LimitedSubmission>(this.attach_LimitedSubmissions), new Action<LimitedSubmission>(this.detach_LimitedSubmissions));
			this._Sponsor = default(EntityRef<Sponsor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SponsorId", DbType="Int NOT NULL")]
		public int SponsorId
		{
			get
			{
				return this._SponsorId;
			}
			set
			{
				if ((this._SponsorId != value))
				{
					if (this._Sponsor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSponsorIdChanging(value);
					this.SendPropertyChanging();
					this._SponsorId = value;
					this.SendPropertyChanged("SponsorId");
					this.OnSponsorIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProgramName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string ProgramName
		{
			get
			{
				return this._ProgramName;
			}
			set
			{
				if ((this._ProgramName != value))
				{
					this.OnProgramNameChanging(value);
					this.SendPropertyChanging();
					this._ProgramName = value;
					this.SendPropertyChanged("ProgramName");
					this.OnProgramNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="NVarChar(MAX)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(256)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cycle1Post", DbType="NVarChar(256)")]
		public string Cycle1Post
		{
			get
			{
				return this._Cycle1Post;
			}
			set
			{
				if ((this._Cycle1Post != value))
				{
					this.OnCycle1PostChanging(value);
					this.SendPropertyChanging();
					this._Cycle1Post = value;
					this.SendPropertyChanged("Cycle1Post");
					this.OnCycle1PostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cycle2Post", DbType="NVarChar(256)")]
		public string Cycle2Post
		{
			get
			{
				return this._Cycle2Post;
			}
			set
			{
				if ((this._Cycle2Post != value))
				{
					this.OnCycle2PostChanging(value);
					this.SendPropertyChanging();
					this._Cycle2Post = value;
					this.SendPropertyChanged("Cycle2Post");
					this.OnCycle2PostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cycle3Post", DbType="NVarChar(256)")]
		public string Cycle3Post
		{
			get
			{
				return this._Cycle3Post;
			}
			set
			{
				if ((this._Cycle3Post != value))
				{
					this.OnCycle3PostChanging(value);
					this.SendPropertyChanging();
					this._Cycle3Post = value;
					this.SendPropertyChanged("Cycle3Post");
					this.OnCycle3PostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cycle1Due", DbType="NVarChar(256)")]
		public string Cycle1Due
		{
			get
			{
				return this._Cycle1Due;
			}
			set
			{
				if ((this._Cycle1Due != value))
				{
					this.OnCycle1DueChanging(value);
					this.SendPropertyChanging();
					this._Cycle1Due = value;
					this.SendPropertyChanged("Cycle1Due");
					this.OnCycle1DueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cycle2Due", DbType="NVarChar(256)")]
		public string Cycle2Due
		{
			get
			{
				return this._Cycle2Due;
			}
			set
			{
				if ((this._Cycle2Due != value))
				{
					this.OnCycle2DueChanging(value);
					this.SendPropertyChanging();
					this._Cycle2Due = value;
					this.SendPropertyChanged("Cycle2Due");
					this.OnCycle2DueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cycle3Due", DbType="NVarChar(256)")]
		public string Cycle3Due
		{
			get
			{
				return this._Cycle3Due;
			}
			set
			{
				if ((this._Cycle3Due != value))
				{
					this.OnCycle3DueChanging(value);
					this.SendPropertyChanging();
					this._Cycle3Due = value;
					this.SendPropertyChanged("Cycle3Due");
					this.OnCycle3DueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostStatus", DbType="Int")]
		public System.Nullable<int> PostStatus
		{
			get
			{
				return this._PostStatus;
			}
			set
			{
				if ((this._PostStatus != value))
				{
					this.OnPostStatusChanging(value);
					this.SendPropertyChanging();
					this._PostStatus = value;
					this.SendPropertyChanged("PostStatus");
					this.OnPostStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this.OnAddedOnChanging(value);
					this.SendPropertyChanging();
					this._AddedOn = value;
					this.SendPropertyChanged("AddedOn");
					this.OnAddedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddedBy", DbType="NVarChar(64)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this.OnAddedByChanging(value);
					this.SendPropertyChanging();
					this._AddedBy = value;
					this.SendPropertyChanged("AddedBy");
					this.OnAddedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(MAX)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegacyMsAccessData", DbType="Bit NOT NULL")]
		public bool LegacyMsAccessData
		{
			get
			{
				return this._LegacyMsAccessData;
			}
			set
			{
				if ((this._LegacyMsAccessData != value))
				{
					this.OnLegacyMsAccessDataChanging(value);
					this.SendPropertyChanging();
					this._LegacyMsAccessData = value;
					this.SendPropertyChanged("LegacyMsAccessData");
					this.OnLegacyMsAccessDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Program_LimitedSubmission", Storage="_LimitedSubmissions", ThisKey="Id", OtherKey="ProgramId")]
		public EntitySet<LimitedSubmission> LimitedSubmissions
		{
			get
			{
				return this._LimitedSubmissions;
			}
			set
			{
				this._LimitedSubmissions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sponsor_Program", Storage="_Sponsor", ThisKey="SponsorId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Sponsor Sponsor
		{
			get
			{
				return this._Sponsor.Entity;
			}
			set
			{
				Sponsor previousValue = this._Sponsor.Entity;
				if (((previousValue != value) 
							|| (this._Sponsor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sponsor.Entity = null;
						previousValue.Programs.Remove(this);
					}
					this._Sponsor.Entity = value;
					if ((value != null))
					{
						value.Programs.Add(this);
						this._SponsorId = value.Id;
					}
					else
					{
						this._SponsorId = default(int);
					}
					this.SendPropertyChanged("Sponsor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LimitedSubmissions(LimitedSubmission entity)
		{
			this.SendPropertyChanging();
			entity.Program = this;
		}
		
		private void detach_LimitedSubmissions(LimitedSubmission entity)
		{
			this.SendPropertyChanging();
			entity.Program = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LTD_Applications")]
	public partial class Application : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _LimitedSubmissionId;
		
		private int _DivisionId;
		
		private string _Kerberos;
		
		private bool _IsNominee;
		
		private int _Rank;
		
		private System.Nullable<bool> _Declined;
		
		private System.Nullable<bool> _Alternate;
		
		private System.Nullable<bool> _IsEligible;
		
		private string _AdminNameToNotify;
		
		private string _AdminEmailToNotify;
		
		private System.Nullable<bool> _NofityAdminOnlyIfNominated;
		
		private System.Nullable<System.DateTime> _AppliedOn;
		
		private bool _LegacyMsAccessData;
		
		private string _ProjectTitle;
		
		private string _ProjectPeriod;
		
		private System.Nullable<decimal> _ProjectAmountRequested;
		
		private System.Nullable<decimal> _ProjectAmountOfCampusMatch;
		
		private string _ProjectOruOrDept;
		
		private System.Nullable<bool> _ProjectHasPreviousPreproposal;
		
		private System.Nullable<int> _ProjectPreviousPreproposalYear;
		
		private System.Nullable<bool> _ProjectHasPreviousFullProposal;
		
		private string _ProjectPreviousFullProposalSponsorComments;
		
		private string _ProjectComments;
		
		private System.Nullable<decimal> _BudgetPersonnelFaculty;
		
		private System.Nullable<decimal> _BudgetPersonnelGrad;
		
		private System.Nullable<decimal> _BudgetPersonnelPostDoc;
		
		private System.Nullable<decimal> _BudgetPersonnelStaffAssoc;
		
		private System.Nullable<decimal> _BudgetPersonnelAdmin;
		
		private System.Nullable<decimal> _BudgetTravelDomestic;
		
		private System.Nullable<decimal> _BudgetTravelForeign;
		
		private System.Nullable<decimal> _BudgetOtherSupplies;
		
		private System.Nullable<decimal> _BudgetOtherTuitionAndFees;
		
		private System.Nullable<decimal> _BudgetIndirectCostBase;
		
		private System.Nullable<decimal> _BudgetIndirectCosts;
		
		private string _BudgetComments;
		
		private System.Nullable<int> _Status;
		
		private EntityRef<LimitedSubmission> _LimitedSubmission;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLimitedSubmissionIdChanging(int value);
    partial void OnLimitedSubmissionIdChanged();
    partial void OnDivisionIdChanging(int value);
    partial void OnDivisionIdChanged();
    partial void OnKerberosChanging(string value);
    partial void OnKerberosChanged();
    partial void OnIsNomineeChanging(bool value);
    partial void OnIsNomineeChanged();
    partial void OnRankChanging(int value);
    partial void OnRankChanged();
    partial void OnDeclinedChanging(System.Nullable<bool> value);
    partial void OnDeclinedChanged();
    partial void OnAlternateChanging(System.Nullable<bool> value);
    partial void OnAlternateChanged();
    partial void OnIsEligibleChanging(System.Nullable<bool> value);
    partial void OnIsEligibleChanged();
    partial void OnAdminNameToNotifyChanging(string value);
    partial void OnAdminNameToNotifyChanged();
    partial void OnAdminEmailToNotifyChanging(string value);
    partial void OnAdminEmailToNotifyChanged();
    partial void OnNofityAdminOnlyIfNominatedChanging(System.Nullable<bool> value);
    partial void OnNofityAdminOnlyIfNominatedChanged();
    partial void OnAppliedOnChanging(System.Nullable<System.DateTime> value);
    partial void OnAppliedOnChanged();
    partial void OnLegacyMsAccessDataChanging(bool value);
    partial void OnLegacyMsAccessDataChanged();
    partial void OnProjectTitleChanging(string value);
    partial void OnProjectTitleChanged();
    partial void OnProjectPeriodChanging(string value);
    partial void OnProjectPeriodChanged();
    partial void OnProjectAmountRequestedChanging(System.Nullable<decimal> value);
    partial void OnProjectAmountRequestedChanged();
    partial void OnProjectAmountOfCampusMatchChanging(System.Nullable<decimal> value);
    partial void OnProjectAmountOfCampusMatchChanged();
    partial void OnProjectOruOrDeptChanging(string value);
    partial void OnProjectOruOrDeptChanged();
    partial void OnProjectHasPreviousPreproposalChanging(System.Nullable<bool> value);
    partial void OnProjectHasPreviousPreproposalChanged();
    partial void OnProjectPreviousPreproposalYearChanging(System.Nullable<int> value);
    partial void OnProjectPreviousPreproposalYearChanged();
    partial void OnProjectHasPreviousFullProposalChanging(System.Nullable<bool> value);
    partial void OnProjectHasPreviousFullProposalChanged();
    partial void OnProjectPreviousFullProposalSponsorCommentsChanging(string value);
    partial void OnProjectPreviousFullProposalSponsorCommentsChanged();
    partial void OnProjectCommentsChanging(string value);
    partial void OnProjectCommentsChanged();
    partial void OnBudgetPersonnelFacultyChanging(System.Nullable<decimal> value);
    partial void OnBudgetPersonnelFacultyChanged();
    partial void OnBudgetPersonnelGradChanging(System.Nullable<decimal> value);
    partial void OnBudgetPersonnelGradChanged();
    partial void OnBudgetPersonnelPostDocChanging(System.Nullable<decimal> value);
    partial void OnBudgetPersonnelPostDocChanged();
    partial void OnBudgetPersonnelStaffAssocChanging(System.Nullable<decimal> value);
    partial void OnBudgetPersonnelStaffAssocChanged();
    partial void OnBudgetPersonnelAdminChanging(System.Nullable<decimal> value);
    partial void OnBudgetPersonnelAdminChanged();
    partial void OnBudgetTravelDomesticChanging(System.Nullable<decimal> value);
    partial void OnBudgetTravelDomesticChanged();
    partial void OnBudgetTravelForeignChanging(System.Nullable<decimal> value);
    partial void OnBudgetTravelForeignChanged();
    partial void OnBudgetOtherSuppliesChanging(System.Nullable<decimal> value);
    partial void OnBudgetOtherSuppliesChanged();
    partial void OnBudgetOtherTuitionAndFeesChanging(System.Nullable<decimal> value);
    partial void OnBudgetOtherTuitionAndFeesChanged();
    partial void OnBudgetIndirectCostBaseChanging(System.Nullable<decimal> value);
    partial void OnBudgetIndirectCostBaseChanged();
    partial void OnBudgetIndirectCostsChanging(System.Nullable<decimal> value);
    partial void OnBudgetIndirectCostsChanged();
    partial void OnBudgetCommentsChanging(string value);
    partial void OnBudgetCommentsChanged();
    partial void OnStatusChanging(System.Nullable<int> value);
    partial void OnStatusChanged();
    #endregion
		
		public Application()
		{
			this._LimitedSubmission = default(EntityRef<LimitedSubmission>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LimitedSubmissionId", DbType="Int NOT NULL")]
		public int LimitedSubmissionId
		{
			get
			{
				return this._LimitedSubmissionId;
			}
			set
			{
				if ((this._LimitedSubmissionId != value))
				{
					if (this._LimitedSubmission.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLimitedSubmissionIdChanging(value);
					this.SendPropertyChanging();
					this._LimitedSubmissionId = value;
					this.SendPropertyChanged("LimitedSubmissionId");
					this.OnLimitedSubmissionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DivisionId", DbType="Int NOT NULL")]
		public int DivisionId
		{
			get
			{
				return this._DivisionId;
			}
			set
			{
				if ((this._DivisionId != value))
				{
					this.OnDivisionIdChanging(value);
					this.SendPropertyChanging();
					this._DivisionId = value;
					this.SendPropertyChanged("DivisionId");
					this.OnDivisionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kerberos", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string Kerberos
		{
			get
			{
				return this._Kerberos;
			}
			set
			{
				if ((this._Kerberos != value))
				{
					this.OnKerberosChanging(value);
					this.SendPropertyChanging();
					this._Kerberos = value;
					this.SendPropertyChanged("Kerberos");
					this.OnKerberosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNominee", DbType="Bit NOT NULL")]
		public bool IsNominee
		{
			get
			{
				return this._IsNominee;
			}
			set
			{
				if ((this._IsNominee != value))
				{
					this.OnIsNomineeChanging(value);
					this.SendPropertyChanging();
					this._IsNominee = value;
					this.SendPropertyChanged("IsNominee");
					this.OnIsNomineeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="Int NOT NULL")]
		public int Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this.OnRankChanging(value);
					this.SendPropertyChanging();
					this._Rank = value;
					this.SendPropertyChanged("Rank");
					this.OnRankChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Declined", DbType="Bit")]
		public System.Nullable<bool> Declined
		{
			get
			{
				return this._Declined;
			}
			set
			{
				if ((this._Declined != value))
				{
					this.OnDeclinedChanging(value);
					this.SendPropertyChanging();
					this._Declined = value;
					this.SendPropertyChanged("Declined");
					this.OnDeclinedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alternate", DbType="Bit")]
		public System.Nullable<bool> Alternate
		{
			get
			{
				return this._Alternate;
			}
			set
			{
				if ((this._Alternate != value))
				{
					this.OnAlternateChanging(value);
					this.SendPropertyChanging();
					this._Alternate = value;
					this.SendPropertyChanged("Alternate");
					this.OnAlternateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsEligible", DbType="Bit")]
		public System.Nullable<bool> IsEligible
		{
			get
			{
				return this._IsEligible;
			}
			set
			{
				if ((this._IsEligible != value))
				{
					this.OnIsEligibleChanging(value);
					this.SendPropertyChanging();
					this._IsEligible = value;
					this.SendPropertyChanged("IsEligible");
					this.OnIsEligibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminNameToNotify", DbType="NVarChar(256)")]
		public string AdminNameToNotify
		{
			get
			{
				return this._AdminNameToNotify;
			}
			set
			{
				if ((this._AdminNameToNotify != value))
				{
					this.OnAdminNameToNotifyChanging(value);
					this.SendPropertyChanging();
					this._AdminNameToNotify = value;
					this.SendPropertyChanged("AdminNameToNotify");
					this.OnAdminNameToNotifyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminEmailToNotify", DbType="NVarChar(256)")]
		public string AdminEmailToNotify
		{
			get
			{
				return this._AdminEmailToNotify;
			}
			set
			{
				if ((this._AdminEmailToNotify != value))
				{
					this.OnAdminEmailToNotifyChanging(value);
					this.SendPropertyChanging();
					this._AdminEmailToNotify = value;
					this.SendPropertyChanged("AdminEmailToNotify");
					this.OnAdminEmailToNotifyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NofityAdminOnlyIfNominated", DbType="Bit")]
		public System.Nullable<bool> NofityAdminOnlyIfNominated
		{
			get
			{
				return this._NofityAdminOnlyIfNominated;
			}
			set
			{
				if ((this._NofityAdminOnlyIfNominated != value))
				{
					this.OnNofityAdminOnlyIfNominatedChanging(value);
					this.SendPropertyChanging();
					this._NofityAdminOnlyIfNominated = value;
					this.SendPropertyChanged("NofityAdminOnlyIfNominated");
					this.OnNofityAdminOnlyIfNominatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AppliedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AppliedOn
		{
			get
			{
				return this._AppliedOn;
			}
			set
			{
				if ((this._AppliedOn != value))
				{
					this.OnAppliedOnChanging(value);
					this.SendPropertyChanging();
					this._AppliedOn = value;
					this.SendPropertyChanged("AppliedOn");
					this.OnAppliedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LegacyMsAccessData", DbType="Bit NOT NULL")]
		public bool LegacyMsAccessData
		{
			get
			{
				return this._LegacyMsAccessData;
			}
			set
			{
				if ((this._LegacyMsAccessData != value))
				{
					this.OnLegacyMsAccessDataChanging(value);
					this.SendPropertyChanging();
					this._LegacyMsAccessData = value;
					this.SendPropertyChanged("LegacyMsAccessData");
					this.OnLegacyMsAccessDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectTitle", DbType="NVarChar(1024)")]
		public string ProjectTitle
		{
			get
			{
				return this._ProjectTitle;
			}
			set
			{
				if ((this._ProjectTitle != value))
				{
					this.OnProjectTitleChanging(value);
					this.SendPropertyChanging();
					this._ProjectTitle = value;
					this.SendPropertyChanged("ProjectTitle");
					this.OnProjectTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectPeriod", DbType="NChar(512)")]
		public string ProjectPeriod
		{
			get
			{
				return this._ProjectPeriod;
			}
			set
			{
				if ((this._ProjectPeriod != value))
				{
					this.OnProjectPeriodChanging(value);
					this.SendPropertyChanging();
					this._ProjectPeriod = value;
					this.SendPropertyChanged("ProjectPeriod");
					this.OnProjectPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectAmountRequested", DbType="Money")]
		public System.Nullable<decimal> ProjectAmountRequested
		{
			get
			{
				return this._ProjectAmountRequested;
			}
			set
			{
				if ((this._ProjectAmountRequested != value))
				{
					this.OnProjectAmountRequestedChanging(value);
					this.SendPropertyChanging();
					this._ProjectAmountRequested = value;
					this.SendPropertyChanged("ProjectAmountRequested");
					this.OnProjectAmountRequestedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectAmountOfCampusMatch", DbType="Money")]
		public System.Nullable<decimal> ProjectAmountOfCampusMatch
		{
			get
			{
				return this._ProjectAmountOfCampusMatch;
			}
			set
			{
				if ((this._ProjectAmountOfCampusMatch != value))
				{
					this.OnProjectAmountOfCampusMatchChanging(value);
					this.SendPropertyChanging();
					this._ProjectAmountOfCampusMatch = value;
					this.SendPropertyChanged("ProjectAmountOfCampusMatch");
					this.OnProjectAmountOfCampusMatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectOruOrDept", DbType="NVarChar(256)")]
		public string ProjectOruOrDept
		{
			get
			{
				return this._ProjectOruOrDept;
			}
			set
			{
				if ((this._ProjectOruOrDept != value))
				{
					this.OnProjectOruOrDeptChanging(value);
					this.SendPropertyChanging();
					this._ProjectOruOrDept = value;
					this.SendPropertyChanged("ProjectOruOrDept");
					this.OnProjectOruOrDeptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectHasPreviousPreproposal", DbType="Bit")]
		public System.Nullable<bool> ProjectHasPreviousPreproposal
		{
			get
			{
				return this._ProjectHasPreviousPreproposal;
			}
			set
			{
				if ((this._ProjectHasPreviousPreproposal != value))
				{
					this.OnProjectHasPreviousPreproposalChanging(value);
					this.SendPropertyChanging();
					this._ProjectHasPreviousPreproposal = value;
					this.SendPropertyChanged("ProjectHasPreviousPreproposal");
					this.OnProjectHasPreviousPreproposalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectPreviousPreproposalYear", DbType="Int")]
		public System.Nullable<int> ProjectPreviousPreproposalYear
		{
			get
			{
				return this._ProjectPreviousPreproposalYear;
			}
			set
			{
				if ((this._ProjectPreviousPreproposalYear != value))
				{
					this.OnProjectPreviousPreproposalYearChanging(value);
					this.SendPropertyChanging();
					this._ProjectPreviousPreproposalYear = value;
					this.SendPropertyChanged("ProjectPreviousPreproposalYear");
					this.OnProjectPreviousPreproposalYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectHasPreviousFullProposal", DbType="Bit")]
		public System.Nullable<bool> ProjectHasPreviousFullProposal
		{
			get
			{
				return this._ProjectHasPreviousFullProposal;
			}
			set
			{
				if ((this._ProjectHasPreviousFullProposal != value))
				{
					this.OnProjectHasPreviousFullProposalChanging(value);
					this.SendPropertyChanging();
					this._ProjectHasPreviousFullProposal = value;
					this.SendPropertyChanged("ProjectHasPreviousFullProposal");
					this.OnProjectHasPreviousFullProposalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectPreviousFullProposalSponsorComments", DbType="NVarChar(MAX)")]
		public string ProjectPreviousFullProposalSponsorComments
		{
			get
			{
				return this._ProjectPreviousFullProposalSponsorComments;
			}
			set
			{
				if ((this._ProjectPreviousFullProposalSponsorComments != value))
				{
					this.OnProjectPreviousFullProposalSponsorCommentsChanging(value);
					this.SendPropertyChanging();
					this._ProjectPreviousFullProposalSponsorComments = value;
					this.SendPropertyChanged("ProjectPreviousFullProposalSponsorComments");
					this.OnProjectPreviousFullProposalSponsorCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectComments", DbType="NVarChar(MAX)")]
		public string ProjectComments
		{
			get
			{
				return this._ProjectComments;
			}
			set
			{
				if ((this._ProjectComments != value))
				{
					this.OnProjectCommentsChanging(value);
					this.SendPropertyChanging();
					this._ProjectComments = value;
					this.SendPropertyChanged("ProjectComments");
					this.OnProjectCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetPersonnelFaculty", DbType="Money")]
		public System.Nullable<decimal> BudgetPersonnelFaculty
		{
			get
			{
				return this._BudgetPersonnelFaculty;
			}
			set
			{
				if ((this._BudgetPersonnelFaculty != value))
				{
					this.OnBudgetPersonnelFacultyChanging(value);
					this.SendPropertyChanging();
					this._BudgetPersonnelFaculty = value;
					this.SendPropertyChanged("BudgetPersonnelFaculty");
					this.OnBudgetPersonnelFacultyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetPersonnelGrad", DbType="Money")]
		public System.Nullable<decimal> BudgetPersonnelGrad
		{
			get
			{
				return this._BudgetPersonnelGrad;
			}
			set
			{
				if ((this._BudgetPersonnelGrad != value))
				{
					this.OnBudgetPersonnelGradChanging(value);
					this.SendPropertyChanging();
					this._BudgetPersonnelGrad = value;
					this.SendPropertyChanged("BudgetPersonnelGrad");
					this.OnBudgetPersonnelGradChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetPersonnelPostDoc", DbType="Money")]
		public System.Nullable<decimal> BudgetPersonnelPostDoc
		{
			get
			{
				return this._BudgetPersonnelPostDoc;
			}
			set
			{
				if ((this._BudgetPersonnelPostDoc != value))
				{
					this.OnBudgetPersonnelPostDocChanging(value);
					this.SendPropertyChanging();
					this._BudgetPersonnelPostDoc = value;
					this.SendPropertyChanged("BudgetPersonnelPostDoc");
					this.OnBudgetPersonnelPostDocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetPersonnelStaffAssoc", DbType="Money")]
		public System.Nullable<decimal> BudgetPersonnelStaffAssoc
		{
			get
			{
				return this._BudgetPersonnelStaffAssoc;
			}
			set
			{
				if ((this._BudgetPersonnelStaffAssoc != value))
				{
					this.OnBudgetPersonnelStaffAssocChanging(value);
					this.SendPropertyChanging();
					this._BudgetPersonnelStaffAssoc = value;
					this.SendPropertyChanged("BudgetPersonnelStaffAssoc");
					this.OnBudgetPersonnelStaffAssocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetPersonnelAdmin", DbType="Money")]
		public System.Nullable<decimal> BudgetPersonnelAdmin
		{
			get
			{
				return this._BudgetPersonnelAdmin;
			}
			set
			{
				if ((this._BudgetPersonnelAdmin != value))
				{
					this.OnBudgetPersonnelAdminChanging(value);
					this.SendPropertyChanging();
					this._BudgetPersonnelAdmin = value;
					this.SendPropertyChanged("BudgetPersonnelAdmin");
					this.OnBudgetPersonnelAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetTravelDomestic", DbType="Money")]
		public System.Nullable<decimal> BudgetTravelDomestic
		{
			get
			{
				return this._BudgetTravelDomestic;
			}
			set
			{
				if ((this._BudgetTravelDomestic != value))
				{
					this.OnBudgetTravelDomesticChanging(value);
					this.SendPropertyChanging();
					this._BudgetTravelDomestic = value;
					this.SendPropertyChanged("BudgetTravelDomestic");
					this.OnBudgetTravelDomesticChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetTravelForeign", DbType="Money")]
		public System.Nullable<decimal> BudgetTravelForeign
		{
			get
			{
				return this._BudgetTravelForeign;
			}
			set
			{
				if ((this._BudgetTravelForeign != value))
				{
					this.OnBudgetTravelForeignChanging(value);
					this.SendPropertyChanging();
					this._BudgetTravelForeign = value;
					this.SendPropertyChanged("BudgetTravelForeign");
					this.OnBudgetTravelForeignChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetOtherSupplies", DbType="Money")]
		public System.Nullable<decimal> BudgetOtherSupplies
		{
			get
			{
				return this._BudgetOtherSupplies;
			}
			set
			{
				if ((this._BudgetOtherSupplies != value))
				{
					this.OnBudgetOtherSuppliesChanging(value);
					this.SendPropertyChanging();
					this._BudgetOtherSupplies = value;
					this.SendPropertyChanged("BudgetOtherSupplies");
					this.OnBudgetOtherSuppliesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetOtherTuitionAndFees", DbType="Money")]
		public System.Nullable<decimal> BudgetOtherTuitionAndFees
		{
			get
			{
				return this._BudgetOtherTuitionAndFees;
			}
			set
			{
				if ((this._BudgetOtherTuitionAndFees != value))
				{
					this.OnBudgetOtherTuitionAndFeesChanging(value);
					this.SendPropertyChanging();
					this._BudgetOtherTuitionAndFees = value;
					this.SendPropertyChanged("BudgetOtherTuitionAndFees");
					this.OnBudgetOtherTuitionAndFeesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetIndirectCostBase", DbType="Money")]
		public System.Nullable<decimal> BudgetIndirectCostBase
		{
			get
			{
				return this._BudgetIndirectCostBase;
			}
			set
			{
				if ((this._BudgetIndirectCostBase != value))
				{
					this.OnBudgetIndirectCostBaseChanging(value);
					this.SendPropertyChanging();
					this._BudgetIndirectCostBase = value;
					this.SendPropertyChanged("BudgetIndirectCostBase");
					this.OnBudgetIndirectCostBaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetIndirectCosts", DbType="Money")]
		public System.Nullable<decimal> BudgetIndirectCosts
		{
			get
			{
				return this._BudgetIndirectCosts;
			}
			set
			{
				if ((this._BudgetIndirectCosts != value))
				{
					this.OnBudgetIndirectCostsChanging(value);
					this.SendPropertyChanging();
					this._BudgetIndirectCosts = value;
					this.SendPropertyChanged("BudgetIndirectCosts");
					this.OnBudgetIndirectCostsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BudgetComments", DbType="NVarChar(MAX)")]
		public string BudgetComments
		{
			get
			{
				return this._BudgetComments;
			}
			set
			{
				if ((this._BudgetComments != value))
				{
					this.OnBudgetCommentsChanging(value);
					this.SendPropertyChanging();
					this._BudgetComments = value;
					this.SendPropertyChanged("BudgetComments");
					this.OnBudgetCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LimitedSubmission_LTD_Application", Storage="_LimitedSubmission", ThisKey="LimitedSubmissionId", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public LimitedSubmission LimitedSubmission
		{
			get
			{
				return this._LimitedSubmission.Entity;
			}
			set
			{
				LimitedSubmission previousValue = this._LimitedSubmission.Entity;
				if (((previousValue != value) 
							|| (this._LimitedSubmission.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LimitedSubmission.Entity = null;
						previousValue.Applications.Remove(this);
					}
					this._LimitedSubmission.Entity = value;
					if ((value != null))
					{
						value.Applications.Add(this);
						this._LimitedSubmissionId = value.Id;
					}
					else
					{
						this._LimitedSubmissionId = default(int);
					}
					this.SendPropertyChanged("LimitedSubmission");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
