//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchasing.WS.AzureStorage {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExportInput", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.SqlServer.Management.Dac.Servic" +
        "eTypes")]
    [System.SerializableAttribute()]
    public partial class ExportInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Purchasing.WS.AzureStorage.BlobCredentials BlobCredentialsField;
        
        private Purchasing.WS.AzureStorage.ConnectionInfo ConnectionInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Purchasing.WS.AzureStorage.BlobCredentials BlobCredentials {
            get {
                return this.BlobCredentialsField;
            }
            set {
                if ((object.ReferenceEquals(this.BlobCredentialsField, value) != true)) {
                    this.BlobCredentialsField = value;
                    this.RaisePropertyChanged("BlobCredentials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Purchasing.WS.AzureStorage.ConnectionInfo ConnectionInfo {
            get {
                return this.ConnectionInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionInfoField, value) != true)) {
                    this.ConnectionInfoField = value;
                    this.RaisePropertyChanged("ConnectionInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlobCredentials", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.SqlServer.Management.Dac.Servic" +
        "eTypes")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Purchasing.WS.AzureStorage.BlobSharedAccessKeyCredentials))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Purchasing.WS.AzureStorage.BlobStorageAccessKeyCredentials))]
    public partial class BlobCredentials : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uri {
            get {
                return this.UriField;
            }
            set {
                if ((object.ReferenceEquals(this.UriField, value) != true)) {
                    this.UriField = value;
                    this.RaisePropertyChanged("Uri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionInfo", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.SqlServer.Management.Dac.Servic" +
        "eTypes")]
    [System.SerializableAttribute()]
    public partial class ConnectionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatabaseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatabaseName {
            get {
                return this.DatabaseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DatabaseNameField, value) != true)) {
                    this.DatabaseNameField = value;
                    this.RaisePropertyChanged("DatabaseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerName {
            get {
                return this.ServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerNameField, value) != true)) {
                    this.ServerNameField = value;
                    this.RaisePropertyChanged("ServerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlobSharedAccessKeyCredentials", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.SqlServer.Management.Dac.Servic" +
        "eTypes")]
    [System.SerializableAttribute()]
    public partial class BlobSharedAccessKeyCredentials : Purchasing.WS.AzureStorage.BlobCredentials {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SharedAccessKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SharedAccessKey {
            get {
                return this.SharedAccessKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SharedAccessKeyField, value) != true)) {
                    this.SharedAccessKeyField = value;
                    this.RaisePropertyChanged("SharedAccessKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlobStorageAccessKeyCredentials", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.SqlServer.Management.Dac.Servic" +
        "eTypes")]
    [System.SerializableAttribute()]
    public partial class BlobStorageAccessKeyCredentials : Purchasing.WS.AzureStorage.BlobCredentials {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StorageAccessKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StorageAccessKey {
            get {
                return this.StorageAccessKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.StorageAccessKeyField, value) != true)) {
                    this.StorageAccessKeyField = value;
                    this.RaisePropertyChanged("StorageAccessKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SelectiveExportInput", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.SqlServer.Management.Dac.Servic" +
        "eTypes")]
    [System.SerializableAttribute()]
    public partial class SelectiveExportInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Purchasing.WS.AzureStorage.BlobCredentials BlobCredentialsField;
        
        private Purchasing.WS.AzureStorage.ConnectionInfo ConnectionInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Purchasing.WS.AzureStorage.TableName[] TablesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Purchasing.WS.AzureStorage.BlobCredentials BlobCredentials {
            get {
                return this.BlobCredentialsField;
            }
            set {
                if ((object.ReferenceEquals(this.BlobCredentialsField, value) != true)) {
                    this.BlobCredentialsField = value;
                    this.RaisePropertyChanged("BlobCredentials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Purchasing.WS.AzureStorage.ConnectionInfo ConnectionInfo {
            get {
                return this.ConnectionInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionInfoField, value) != true)) {
                    this.ConnectionInfoField = value;
                    this.RaisePropertyChanged("ConnectionInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Purchasing.WS.AzureStorage.TableName[] Tables {
            get {
                return this.TablesField;
            }
            set {
                if ((object.ReferenceEquals(this.TablesField, value) != true)) {
                    this.TablesField = value;
                    this.RaisePropertyChanged("Tables");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableName", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.SqlServer.Management.Dac.Servic" +
        "eTypes")]
    [System.SerializableAttribute()]
    public partial class TableName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchemaNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchemaName {
            get {
                return this.SchemaNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SchemaNameField, value) != true)) {
                    this.SchemaNameField = value;
                    this.RaisePropertyChanged("SchemaName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportInput", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.SqlServer.Management.Dac.Servic" +
        "eTypes")]
    [System.SerializableAttribute()]
    public partial class ImportInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AzureEditionField;
        
        private Purchasing.WS.AzureStorage.BlobCredentials BlobCredentialsField;
        
        private Purchasing.WS.AzureStorage.ConnectionInfo ConnectionInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DatabaseSizeInGBField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AzureEdition {
            get {
                return this.AzureEditionField;
            }
            set {
                if ((object.ReferenceEquals(this.AzureEditionField, value) != true)) {
                    this.AzureEditionField = value;
                    this.RaisePropertyChanged("AzureEdition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Purchasing.WS.AzureStorage.BlobCredentials BlobCredentials {
            get {
                return this.BlobCredentialsField;
            }
            set {
                if ((object.ReferenceEquals(this.BlobCredentialsField, value) != true)) {
                    this.BlobCredentialsField = value;
                    this.RaisePropertyChanged("BlobCredentials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public Purchasing.WS.AzureStorage.ConnectionInfo ConnectionInfo {
            get {
                return this.ConnectionInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionInfoField, value) != true)) {
                    this.ConnectionInfoField = value;
                    this.RaisePropertyChanged("ConnectionInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DatabaseSizeInGB {
            get {
                return this.DatabaseSizeInGBField;
            }
            set {
                if ((this.DatabaseSizeInGBField.Equals(value) != true)) {
                    this.DatabaseSizeInGBField = value;
                    this.RaisePropertyChanged("DatabaseSizeInGB");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusInput", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.SqlServer.Management.Dac.Servic" +
        "eTypes")]
    [System.SerializableAttribute()]
    public partial class StatusInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        private string ServerNameField;
        
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ServerName {
            get {
                return this.ServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerNameField, value) != true)) {
                    this.ServerNameField = value;
                    this.RaisePropertyChanged("ServerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusInfo", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.SqlServer.Management.Dac.Servic" +
        "eTypes")]
    [System.SerializableAttribute()]
    public partial class StatusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlobUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DatabaseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime QueuedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlobUri {
            get {
                return this.BlobUriField;
            }
            set {
                if ((object.ReferenceEquals(this.BlobUriField, value) != true)) {
                    this.BlobUriField = value;
                    this.RaisePropertyChanged("BlobUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DatabaseName {
            get {
                return this.DatabaseNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DatabaseNameField, value) != true)) {
                    this.DatabaseNameField = value;
                    this.RaisePropertyChanged("DatabaseName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModifiedTime {
            get {
                return this.LastModifiedTimeField;
            }
            set {
                if ((this.LastModifiedTimeField.Equals(value) != true)) {
                    this.LastModifiedTimeField = value;
                    this.RaisePropertyChanged("LastModifiedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime QueuedTime {
            get {
                return this.QueuedTimeField;
            }
            set {
                if ((this.QueuedTimeField.Equals(value) != true)) {
                    this.QueuedTimeField = value;
                    this.RaisePropertyChanged("QueuedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestType {
            get {
                return this.RequestTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestTypeField, value) != true)) {
                    this.RequestTypeField = value;
                    this.RaisePropertyChanged("RequestType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerName {
            get {
                return this.ServerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerNameField, value) != true)) {
                    this.ServerNameField = value;
                    this.RaisePropertyChanged("ServerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AzureStorage.IDACWebService")]
    public interface IDACWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDACWebService/Export", ReplyAction="http://tempuri.org/IDACWebService/ExportResponse")]
        Purchasing.WS.AzureStorage.ExportResponse Export(Purchasing.WS.AzureStorage.ExportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDACWebService/SelectiveExport", ReplyAction="http://tempuri.org/IDACWebService/SelectiveExportResponse")]
        Purchasing.WS.AzureStorage.SelectiveExportResponse SelectiveExport(Purchasing.WS.AzureStorage.SelectiveExportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDACWebService/ExportWithMaskedData", ReplyAction="http://tempuri.org/IDACWebService/ExportWithMaskedDataResponse")]
        Purchasing.WS.AzureStorage.ExportWithMaskedDataResponse ExportWithMaskedData(Purchasing.WS.AzureStorage.ExportWithMaskedDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDACWebService/Import", ReplyAction="http://tempuri.org/IDACWebService/ImportResponse")]
        Purchasing.WS.AzureStorage.ImportResponse Import(Purchasing.WS.AzureStorage.ImportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDACWebService/PostStatus", ReplyAction="http://tempuri.org/IDACWebService/PostStatusResponse")]
        Purchasing.WS.AzureStorage.PostStatusResponse PostStatus(Purchasing.WS.AzureStorage.PostStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDACWebService/GetStatus", ReplyAction="http://tempuri.org/IDACWebService/GetStatusResponse")]
        Purchasing.WS.AzureStorage.GetStatusResponse GetStatus(Purchasing.WS.AzureStorage.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDACWebService/Test", ReplyAction="http://tempuri.org/IDACWebService/TestResponse")]
        Purchasing.WS.AzureStorage.TestResponse Test(Purchasing.WS.AzureStorage.TestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Export", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Purchasing.WS.AzureStorage.ExportInput exportInput;
        
        public ExportRequest() {
        }
        
        public ExportRequest(Purchasing.WS.AzureStorage.ExportInput exportInput) {
            this.exportInput = exportInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid ExportResult;
        
        public ExportResponse() {
        }
        
        public ExportResponse(System.Guid ExportResult) {
            this.ExportResult = ExportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectiveExport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectiveExportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Purchasing.WS.AzureStorage.SelectiveExportInput exportInput;
        
        public SelectiveExportRequest() {
        }
        
        public SelectiveExportRequest(Purchasing.WS.AzureStorage.SelectiveExportInput exportInput) {
            this.exportInput = exportInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectiveExportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectiveExportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid SelectiveExportResult;
        
        public SelectiveExportResponse() {
        }
        
        public SelectiveExportResponse(System.Guid SelectiveExportResult) {
            this.SelectiveExportResult = SelectiveExportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportWithMaskedData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportWithMaskedDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Purchasing.WS.AzureStorage.ExportInput exportInput;
        
        public ExportWithMaskedDataRequest() {
        }
        
        public ExportWithMaskedDataRequest(Purchasing.WS.AzureStorage.ExportInput exportInput) {
            this.exportInput = exportInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExportWithMaskedDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExportWithMaskedDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid ExportWithMaskedDataResult;
        
        public ExportWithMaskedDataResponse() {
        }
        
        public ExportWithMaskedDataResponse(System.Guid ExportWithMaskedDataResult) {
            this.ExportWithMaskedDataResult = ExportWithMaskedDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Import", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Purchasing.WS.AzureStorage.ImportInput importInput;
        
        public ImportRequest() {
        }
        
        public ImportRequest(Purchasing.WS.AzureStorage.ImportInput importInput) {
            this.importInput = importInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid ImportResult;
        
        public ImportResponse() {
        }
        
        public ImportResponse(System.Guid ImportResult) {
            this.ImportResult = ImportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PostStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Purchasing.WS.AzureStorage.StatusInput statusInput;
        
        public PostStatusRequest() {
        }
        
        public PostStatusRequest(Purchasing.WS.AzureStorage.StatusInput statusInput) {
            this.statusInput = statusInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PostStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PostStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Purchasing.WS.AzureStorage.StatusInfo[] PostStatusResult;
        
        public PostStatusResponse() {
        }
        
        public PostStatusResponse(Purchasing.WS.AzureStorage.StatusInfo[] PostStatusResult) {
            this.PostStatusResult = PostStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string serverName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string userName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string requestId;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(string serverName, string userName, string password, string requestId) {
            this.serverName = serverName;
            this.userName = userName;
            this.password = password;
            this.requestId = requestId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Purchasing.WS.AzureStorage.StatusInfo[] GetStatusResult;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(Purchasing.WS.AzureStorage.StatusInfo[] GetStatusResult) {
            this.GetStatusResult = GetStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Test", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestRequest {
        
        public TestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int TestResult;
        
        public TestResponse() {
        }
        
        public TestResponse(int TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDACWebServiceChannel : Purchasing.WS.AzureStorage.IDACWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DACWebServiceClient : System.ServiceModel.ClientBase<Purchasing.WS.AzureStorage.IDACWebService>, Purchasing.WS.AzureStorage.IDACWebService {
        
        public DACWebServiceClient() {
        }
        
        public DACWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DACWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DACWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DACWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Purchasing.WS.AzureStorage.ExportResponse Export(Purchasing.WS.AzureStorage.ExportRequest request) {
            return base.Channel.Export(request);
        }
        
        public Purchasing.WS.AzureStorage.SelectiveExportResponse SelectiveExport(Purchasing.WS.AzureStorage.SelectiveExportRequest request) {
            return base.Channel.SelectiveExport(request);
        }
        
        public Purchasing.WS.AzureStorage.ExportWithMaskedDataResponse ExportWithMaskedData(Purchasing.WS.AzureStorage.ExportWithMaskedDataRequest request) {
            return base.Channel.ExportWithMaskedData(request);
        }
        
        public Purchasing.WS.AzureStorage.ImportResponse Import(Purchasing.WS.AzureStorage.ImportRequest request) {
            return base.Channel.Import(request);
        }
        
        public Purchasing.WS.AzureStorage.PostStatusResponse PostStatus(Purchasing.WS.AzureStorage.PostStatusRequest request) {
            return base.Channel.PostStatus(request);
        }
        
        public Purchasing.WS.AzureStorage.GetStatusResponse GetStatus(Purchasing.WS.AzureStorage.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public Purchasing.WS.AzureStorage.TestResponse Test(Purchasing.WS.AzureStorage.TestRequest request) {
            return base.Channel.Test(request);
        }
    }
}
