FROM mcr.microsoft.com/devcontainers/dotnet:1-10.0-noble

# see https://github.com/devcontainers/templates/blob/main/src/dotnet-mssql/.devcontainer/Dockerfile
# if you want to setup some more advance sql server stuff