CREATE TABLE [dbo].[EmailPreferences] (
    [Id]                                  VARCHAR (10) NOT NULL,
    [RequesterOrderSubmission]            BIT          NOT NULL,
    [RequesterApproverApproved]           BIT          NOT NULL,
    [RequesterApproverChanged]            BIT          NOT NULL,
    [RequesterAccountManagerApproved]     BIT          NOT NULL,
    [RequesterAccountManagerChanged]      BIT          NOT NULL,
    [RequesterPurchaserAction]            BIT          NOT NULL,
    [RequesterPurchaserChanged]           BIT          NOT NULL,
    [RequesterKualiProcessed]             BIT          NOT NULL,
    [RequesterKualiApproved]              BIT          NOT NULL,
    [ApproverAccountManagerApproved]      BIT          NOT NULL,
    [ApproverAccountManagerDenied]        BIT          NOT NULL,
    [ApproverKualiApproved]               BIT          NOT NULL,
    [ApproverPurchaserProcessed]          BIT          NOT NULL,
    [ApproverOrderCompleted]              BIT          NOT NULL,
    [ApproverOrderArrive]                 BIT          CONSTRAINT [DF_EmailPreferences_ApprovedOrderAssigned] DEFAULT ((1)) NOT NULL,
    [AccountManagerKualiApproved]         BIT          NOT NULL,
    [AccountManagerOrderCompleted]        BIT          NOT NULL,
    [AccountManagerPurchaserProcessed]    BIT          NOT NULL,
    [AccountManagerOrderArrive]           BIT          CONSTRAINT [DF_EmailPreferences_AccountManagerOrderArrive] DEFAULT ((1)) NOT NULL,
    [PurchaserKualiApproved]              BIT          NOT NULL,
    [PurchaserOrderCompleted]             BIT          NOT NULL,
    [PurchaserOrderArrive]                BIT          CONSTRAINT [DF_EmailPreferences_PurchaserOrderArrive] DEFAULT ((1)) NOT NULL,
    [PurchaserKfsItemReceived]            BIT          DEFAULT ((1)) NOT NULL,
    [PurchaserPCardItemReceived]          BIT          DEFAULT ((1)) NOT NULL,
    [PurchaserCampusServicesItemReceived] BIT          DEFAULT ((1)) NOT NULL,
    [NotificationType]                    VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_EmailPreferences] PRIMARY KEY CLUSTERED ([Id] ASC)
);

