//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchasing.WS.PurchaseDocumentService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="purap", ConfigurationName="Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP")]
    public interface purchasingDocumentsInterfaceServiceSOAP
    {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatusResponse getPurchaseRequisitionStatus(Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatus request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatusResponse> getPurchaseRequisitionStatusAsync(Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatus request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Purchasing.WS.PurchaseDocumentService.uploadRequisitionResponse uploadRequisition(Purchasing.WS.PurchaseDocumentService.uploadRequisition request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Purchasing.WS.PurchaseDocumentService.uploadRequisitionResponse> uploadRequisitionAsync(Purchasing.WS.PurchaseDocumentService.uploadRequisition request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Purchasing.WS.PurchaseDocumentService.uploadRequisitionExtendResponse uploadRequisitionExtend(Purchasing.WS.PurchaseDocumentService.uploadRequisitionExtend request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Purchasing.WS.PurchaseDocumentService.uploadRequisitionExtendResponse> uploadRequisitionExtendAsync(Purchasing.WS.PurchaseDocumentService.uploadRequisitionExtend request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'Microsoft.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrlResponse getPurchasingDocumentUrl(Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrl request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrlResponse> getPurchasingDocumentUrlAsync(Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrl request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class purchaseRequisitionStatusInfo : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string documentNumberField;
        
        private string documentUrlField;
        
        private bool fullyPaidField;
        
        private string purchaseOrderDocumentNumberField;
        
        private string purchaseOrderNumberField;
        
        private string purchaseOrderStatusCodeField;
        
        private string purchaseOrderStatusNameField;
        
        private string purchaseOrderTypeCodeField;
        
        private string purchaseRequsitionStatusCodeField;
        
        private string purchaseRequsitionStatusNameField;
        
        private bool receivedField;
        
        private string routeLevelField;
        
        private string routeStatusCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string documentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
                this.RaisePropertyChanged("documentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string documentUrl
        {
            get
            {
                return this.documentUrlField;
            }
            set
            {
                this.documentUrlField = value;
                this.RaisePropertyChanged("documentUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool fullyPaid
        {
            get
            {
                return this.fullyPaidField;
            }
            set
            {
                this.fullyPaidField = value;
                this.RaisePropertyChanged("fullyPaid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string purchaseOrderDocumentNumber
        {
            get
            {
                return this.purchaseOrderDocumentNumberField;
            }
            set
            {
                this.purchaseOrderDocumentNumberField = value;
                this.RaisePropertyChanged("purchaseOrderDocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string purchaseOrderNumber
        {
            get
            {
                return this.purchaseOrderNumberField;
            }
            set
            {
                this.purchaseOrderNumberField = value;
                this.RaisePropertyChanged("purchaseOrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string purchaseOrderStatusCode
        {
            get
            {
                return this.purchaseOrderStatusCodeField;
            }
            set
            {
                this.purchaseOrderStatusCodeField = value;
                this.RaisePropertyChanged("purchaseOrderStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string purchaseOrderStatusName
        {
            get
            {
                return this.purchaseOrderStatusNameField;
            }
            set
            {
                this.purchaseOrderStatusNameField = value;
                this.RaisePropertyChanged("purchaseOrderStatusName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string purchaseOrderTypeCode
        {
            get
            {
                return this.purchaseOrderTypeCodeField;
            }
            set
            {
                this.purchaseOrderTypeCodeField = value;
                this.RaisePropertyChanged("purchaseOrderTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string purchaseRequsitionStatusCode
        {
            get
            {
                return this.purchaseRequsitionStatusCodeField;
            }
            set
            {
                this.purchaseRequsitionStatusCodeField = value;
                this.RaisePropertyChanged("purchaseRequsitionStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string purchaseRequsitionStatusName
        {
            get
            {
                return this.purchaseRequsitionStatusNameField;
            }
            set
            {
                this.purchaseRequsitionStatusNameField = value;
                this.RaisePropertyChanged("purchaseRequsitionStatusName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool received
        {
            get
            {
                return this.receivedField;
            }
            set
            {
                this.receivedField = value;
                this.RaisePropertyChanged("received");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string routeLevel
        {
            get
            {
                return this.routeLevelField;
            }
            set
            {
                this.routeLevelField = value;
                this.RaisePropertyChanged("routeLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string routeStatusCode
        {
            get
            {
                return this.routeStatusCodeField;
            }
            set
            {
                this.routeStatusCodeField = value;
                this.RaisePropertyChanged("routeStatusCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class resultMessage : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string codeField;
        
        private string messageField;
        
        private string severityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class documentCreationResult : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string[] documentNumbersField;
        
        private resultMessage[] messagesField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documentNumbers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] documentNumbers
        {
            get
            {
                return this.documentNumbersField;
            }
            set
            {
                this.documentNumbersField = value;
                this.RaisePropertyChanged("documentNumbers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public resultMessage[] messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class purchasingItemInfo : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private purchasingAccountingInfo[] accountingLinesField;
        
        private string catelogNumberField;
        
        private string commodityCodeField;
        
        private string descriptionField;
        
        private string itemTypeCodeField;
        
        private string quantityField;
        
        private string unitOfMeasureCodeField;
        
        private string unitPriceField;
        
        private string userDefineField1Field;
        
        private string userDefineField2Field;
        
        private string userDefineField3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accountingLines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public purchasingAccountingInfo[] accountingLines
        {
            get
            {
                return this.accountingLinesField;
            }
            set
            {
                this.accountingLinesField = value;
                this.RaisePropertyChanged("accountingLines");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string catelogNumber
        {
            get
            {
                return this.catelogNumberField;
            }
            set
            {
                this.catelogNumberField = value;
                this.RaisePropertyChanged("catelogNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string commodityCode
        {
            get
            {
                return this.commodityCodeField;
            }
            set
            {
                this.commodityCodeField = value;
                this.RaisePropertyChanged("commodityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string itemTypeCode
        {
            get
            {
                return this.itemTypeCodeField;
            }
            set
            {
                this.itemTypeCodeField = value;
                this.RaisePropertyChanged("itemTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string unitOfMeasureCode
        {
            get
            {
                return this.unitOfMeasureCodeField;
            }
            set
            {
                this.unitOfMeasureCodeField = value;
                this.RaisePropertyChanged("unitOfMeasureCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string unitPrice
        {
            get
            {
                return this.unitPriceField;
            }
            set
            {
                this.unitPriceField = value;
                this.RaisePropertyChanged("unitPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string userDefineField1
        {
            get
            {
                return this.userDefineField1Field;
            }
            set
            {
                this.userDefineField1Field = value;
                this.RaisePropertyChanged("userDefineField1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string userDefineField2
        {
            get
            {
                return this.userDefineField2Field;
            }
            set
            {
                this.userDefineField2Field = value;
                this.RaisePropertyChanged("userDefineField2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string userDefineField3
        {
            get
            {
                return this.userDefineField3Field;
            }
            set
            {
                this.userDefineField3Field = value;
                this.RaisePropertyChanged("userDefineField3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class purchasingAccountingInfo : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string accountNumberField;
        
        private string chartOfAccountsCodeField;
        
        private string distributionPercentField;
        
        private string objectCodeField;
        
        private string projectCodeField;
        
        private string subAccountNumberField;
        
        private string subObjectCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
                this.RaisePropertyChanged("accountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string chartOfAccountsCode
        {
            get
            {
                return this.chartOfAccountsCodeField;
            }
            set
            {
                this.chartOfAccountsCodeField = value;
                this.RaisePropertyChanged("chartOfAccountsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string distributionPercent
        {
            get
            {
                return this.distributionPercentField;
            }
            set
            {
                this.distributionPercentField = value;
                this.RaisePropertyChanged("distributionPercent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string objectCode
        {
            get
            {
                return this.objectCodeField;
            }
            set
            {
                this.objectCodeField = value;
                this.RaisePropertyChanged("objectCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string projectCode
        {
            get
            {
                return this.projectCodeField;
            }
            set
            {
                this.projectCodeField = value;
                this.RaisePropertyChanged("projectCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string subAccountNumber
        {
            get
            {
                return this.subAccountNumberField;
            }
            set
            {
                this.subAccountNumberField = value;
                this.RaisePropertyChanged("subAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string subObjectCode
        {
            get
            {
                return this.subObjectCodeField;
            }
            set
            {
                this.subObjectCodeField = value;
                this.RaisePropertyChanged("subObjectCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class documentInfo : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string descriptionField;
        
        private string documentNoteField;
        
        private string explanationField;
        
        private string initiatorUserIdField;
        
        private string organizationTrackingNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string documentNote
        {
            get
            {
                return this.documentNoteField;
            }
            set
            {
                this.documentNoteField = value;
                this.RaisePropertyChanged("documentNote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string explanation
        {
            get
            {
                return this.explanationField;
            }
            set
            {
                this.explanationField = value;
                this.RaisePropertyChanged("explanation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string initiatorUserId
        {
            get
            {
                return this.initiatorUserIdField;
            }
            set
            {
                this.initiatorUserIdField = value;
                this.RaisePropertyChanged("initiatorUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string organizationTrackingNumber
        {
            get
            {
                return this.organizationTrackingNumberField;
            }
            set
            {
                this.organizationTrackingNumberField = value;
                this.RaisePropertyChanged("organizationTrackingNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class purchasingAddressInfo : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string buildingCodeField;
        
        private string campusCodeField;
        
        private string cityNameField;
        
        private string countryCodeField;
        
        private string emailAddressField;
        
        private string nameField;
        
        private string phoneNumberField;
        
        private string roomNumberField;
        
        private string stateCodeField;
        
        private string zipCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string addressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
                this.RaisePropertyChanged("addressLine1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string addressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
                this.RaisePropertyChanged("addressLine2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string buildingCode
        {
            get
            {
                return this.buildingCodeField;
            }
            set
            {
                this.buildingCodeField = value;
                this.RaisePropertyChanged("buildingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string campusCode
        {
            get
            {
                return this.campusCodeField;
            }
            set
            {
                this.campusCodeField = value;
                this.RaisePropertyChanged("campusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cityName
        {
            get
            {
                return this.cityNameField;
            }
            set
            {
                this.cityNameField = value;
                this.RaisePropertyChanged("cityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string countryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string emailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
                this.RaisePropertyChanged("emailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string phoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string roomNumber
        {
            get
            {
                return this.roomNumberField;
            }
            set
            {
                this.roomNumberField = value;
                this.RaisePropertyChanged("roomNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string stateCode
        {
            get
            {
                return this.stateCodeField;
            }
            set
            {
                this.stateCodeField = value;
                this.RaisePropertyChanged("stateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string zipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
                this.RaisePropertyChanged("zipCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class purchasingBelowTheLineItemInfo : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string belowItemAmountField;
        
        private string belowItemDescriptionField;
        
        private purchasingAccountingInfo[] belowItemPurchasingAccountingLinesField;
        
        private string belowItemTaxAmountField;
        
        private string itemTypeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string belowItemAmount
        {
            get
            {
                return this.belowItemAmountField;
            }
            set
            {
                this.belowItemAmountField = value;
                this.RaisePropertyChanged("belowItemAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string belowItemDescription
        {
            get
            {
                return this.belowItemDescriptionField;
            }
            set
            {
                this.belowItemDescriptionField = value;
                this.RaisePropertyChanged("belowItemDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("belowItemPurchasingAccountingLines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public purchasingAccountingInfo[] belowItemPurchasingAccountingLines
        {
            get
            {
                return this.belowItemPurchasingAccountingLinesField;
            }
            set
            {
                this.belowItemPurchasingAccountingLinesField = value;
                this.RaisePropertyChanged("belowItemPurchasingAccountingLines");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string belowItemTaxAmount
        {
            get
            {
                return this.belowItemTaxAmountField;
            }
            set
            {
                this.belowItemTaxAmountField = value;
                this.RaisePropertyChanged("belowItemTaxAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string itemTypeCode
        {
            get
            {
                return this.itemTypeCodeField;
            }
            set
            {
                this.itemTypeCodeField = value;
                this.RaisePropertyChanged("itemTypeCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class purchaseRequisitionInfo : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string agreementNumberField;
        
        private purchasingBelowTheLineItemInfo[] belowTheLineItemsField;
        
        private string chartOfAccountsCodeField;
        
        private string customerNumberField;
        
        private purchasingAddressInfo deliveryAddressField;
        
        private string deliveryInstructionTextField;
        
        private documentInfo documentInfoField;
        
        private purchasingAccountingInfo[] freightAccountingLinesField;
        
        private string freightAmountField;
        
        private purchasingItemInfo[] itemsField;
        
        private string organizationCodeField;
        
        private string priceSourceCodeField;
        
        private string requestTypeCodeField;
        
        private string requestorUserIdField;
        
        private string requiredDateField;
        
        private purchasingAccountingInfo[] shippingAndHandlingAccountingLinesField;
        
        private string shippingAndHandlingAmountField;
        
        private string shippingAndHandlingDescriptionField;
        
        private string sourceSystemOrderIdField;
        
        private string vendorAddressNumberField;
        
        private string vendorContactNameField;
        
        private string vendorContactPhoneNumberField;
        
        private string vendorDetailIdField;
        
        private string vendorHeaderIdField;
        
        private string vendorPaymentTermsCodeField;
        
        private string vendorShippingPaymentTermsCodeField;
        
        private string vendorShippingTitleCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string agreementNumber
        {
            get
            {
                return this.agreementNumberField;
            }
            set
            {
                this.agreementNumberField = value;
                this.RaisePropertyChanged("agreementNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("belowTheLineItems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public purchasingBelowTheLineItemInfo[] belowTheLineItems
        {
            get
            {
                return this.belowTheLineItemsField;
            }
            set
            {
                this.belowTheLineItemsField = value;
                this.RaisePropertyChanged("belowTheLineItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string chartOfAccountsCode
        {
            get
            {
                return this.chartOfAccountsCodeField;
            }
            set
            {
                this.chartOfAccountsCodeField = value;
                this.RaisePropertyChanged("chartOfAccountsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string customerNumber
        {
            get
            {
                return this.customerNumberField;
            }
            set
            {
                this.customerNumberField = value;
                this.RaisePropertyChanged("customerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public purchasingAddressInfo deliveryAddress
        {
            get
            {
                return this.deliveryAddressField;
            }
            set
            {
                this.deliveryAddressField = value;
                this.RaisePropertyChanged("deliveryAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string deliveryInstructionText
        {
            get
            {
                return this.deliveryInstructionTextField;
            }
            set
            {
                this.deliveryInstructionTextField = value;
                this.RaisePropertyChanged("deliveryInstructionText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public documentInfo documentInfo
        {
            get
            {
                return this.documentInfoField;
            }
            set
            {
                this.documentInfoField = value;
                this.RaisePropertyChanged("documentInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("freightAccountingLines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public purchasingAccountingInfo[] freightAccountingLines
        {
            get
            {
                return this.freightAccountingLinesField;
            }
            set
            {
                this.freightAccountingLinesField = value;
                this.RaisePropertyChanged("freightAccountingLines");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string freightAmount
        {
            get
            {
                return this.freightAmountField;
            }
            set
            {
                this.freightAmountField = value;
                this.RaisePropertyChanged("freightAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public purchasingItemInfo[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string organizationCode
        {
            get
            {
                return this.organizationCodeField;
            }
            set
            {
                this.organizationCodeField = value;
                this.RaisePropertyChanged("organizationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string priceSourceCode
        {
            get
            {
                return this.priceSourceCodeField;
            }
            set
            {
                this.priceSourceCodeField = value;
                this.RaisePropertyChanged("priceSourceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string requestTypeCode
        {
            get
            {
                return this.requestTypeCodeField;
            }
            set
            {
                this.requestTypeCodeField = value;
                this.RaisePropertyChanged("requestTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string requestorUserId
        {
            get
            {
                return this.requestorUserIdField;
            }
            set
            {
                this.requestorUserIdField = value;
                this.RaisePropertyChanged("requestorUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string requiredDate
        {
            get
            {
                return this.requiredDateField;
            }
            set
            {
                this.requiredDateField = value;
                this.RaisePropertyChanged("requiredDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shippingAndHandlingAccountingLines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public purchasingAccountingInfo[] shippingAndHandlingAccountingLines
        {
            get
            {
                return this.shippingAndHandlingAccountingLinesField;
            }
            set
            {
                this.shippingAndHandlingAccountingLinesField = value;
                this.RaisePropertyChanged("shippingAndHandlingAccountingLines");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string shippingAndHandlingAmount
        {
            get
            {
                return this.shippingAndHandlingAmountField;
            }
            set
            {
                this.shippingAndHandlingAmountField = value;
                this.RaisePropertyChanged("shippingAndHandlingAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string shippingAndHandlingDescription
        {
            get
            {
                return this.shippingAndHandlingDescriptionField;
            }
            set
            {
                this.shippingAndHandlingDescriptionField = value;
                this.RaisePropertyChanged("shippingAndHandlingDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string sourceSystemOrderId
        {
            get
            {
                return this.sourceSystemOrderIdField;
            }
            set
            {
                this.sourceSystemOrderIdField = value;
                this.RaisePropertyChanged("sourceSystemOrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string vendorAddressNumber
        {
            get
            {
                return this.vendorAddressNumberField;
            }
            set
            {
                this.vendorAddressNumberField = value;
                this.RaisePropertyChanged("vendorAddressNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string vendorContactName
        {
            get
            {
                return this.vendorContactNameField;
            }
            set
            {
                this.vendorContactNameField = value;
                this.RaisePropertyChanged("vendorContactName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string vendorContactPhoneNumber
        {
            get
            {
                return this.vendorContactPhoneNumberField;
            }
            set
            {
                this.vendorContactPhoneNumberField = value;
                this.RaisePropertyChanged("vendorContactPhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string vendorDetailId
        {
            get
            {
                return this.vendorDetailIdField;
            }
            set
            {
                this.vendorDetailIdField = value;
                this.RaisePropertyChanged("vendorDetailId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string vendorHeaderId
        {
            get
            {
                return this.vendorHeaderIdField;
            }
            set
            {
                this.vendorHeaderIdField = value;
                this.RaisePropertyChanged("vendorHeaderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string vendorPaymentTermsCode
        {
            get
            {
                return this.vendorPaymentTermsCodeField;
            }
            set
            {
                this.vendorPaymentTermsCodeField = value;
                this.RaisePropertyChanged("vendorPaymentTermsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string vendorShippingPaymentTermsCode
        {
            get
            {
                return this.vendorShippingPaymentTermsCodeField;
            }
            set
            {
                this.vendorShippingPaymentTermsCodeField = value;
                this.RaisePropertyChanged("vendorShippingPaymentTermsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string vendorShippingTitleCode
        {
            get
            {
                return this.vendorShippingTitleCodeField;
            }
            set
            {
                this.vendorShippingTitleCodeField = value;
                this.RaisePropertyChanged("vendorShippingTitleCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPurchaseRequisitionStatus", WrapperNamespace="purap", IsWrapped=true)]
    public partial class getPurchaseRequisitionStatus
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getPurchaseRequisitionStatus()
        {
        }
        
        public getPurchaseRequisitionStatus(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPurchaseRequisitionStatusResponse", WrapperNamespace="purap", IsWrapped=true)]
    public partial class getPurchaseRequisitionStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Purchasing.WS.PurchaseDocumentService.purchaseRequisitionStatusInfo @return;
        
        public getPurchaseRequisitionStatusResponse()
        {
        }
        
        public getPurchaseRequisitionStatusResponse(Purchasing.WS.PurchaseDocumentService.purchaseRequisitionStatusInfo @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadRequisition", WrapperNamespace="purap", IsWrapped=true)]
    public partial class uploadRequisition
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Purchasing.WS.PurchaseDocumentService.purchaseRequisitionInfo orderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string securityToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string feedOriginationCode;
        
        public uploadRequisition()
        {
        }
        
        public uploadRequisition(Purchasing.WS.PurchaseDocumentService.purchaseRequisitionInfo orderInfo, string securityToken, string feedOriginationCode)
        {
            this.orderInfo = orderInfo;
            this.securityToken = securityToken;
            this.feedOriginationCode = feedOriginationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadRequisitionResponse", WrapperNamespace="purap", IsWrapped=true)]
    public partial class uploadRequisitionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Purchasing.WS.PurchaseDocumentService.documentCreationResult @return;
        
        public uploadRequisitionResponse()
        {
        }
        
        public uploadRequisitionResponse(Purchasing.WS.PurchaseDocumentService.documentCreationResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadRequisitionExtend", WrapperNamespace="purap", IsWrapped=true)]
    public partial class uploadRequisitionExtend
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Purchasing.WS.PurchaseDocumentService.purchaseRequisitionInfo orderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string securityToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string feedOriginationCode;
        
        public uploadRequisitionExtend()
        {
        }
        
        public uploadRequisitionExtend(Purchasing.WS.PurchaseDocumentService.purchaseRequisitionInfo orderInfo, string securityToken, string feedOriginationCode)
        {
            this.orderInfo = orderInfo;
            this.securityToken = securityToken;
            this.feedOriginationCode = feedOriginationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadRequisitionExtendResponse", WrapperNamespace="purap", IsWrapped=true)]
    public partial class uploadRequisitionExtendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Purchasing.WS.PurchaseDocumentService.documentCreationResult @return;
        
        public uploadRequisitionExtendResponse()
        {
        }
        
        public uploadRequisitionExtendResponse(Purchasing.WS.PurchaseDocumentService.documentCreationResult @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPurchasingDocumentUrl", WrapperNamespace="purap", IsWrapped=true)]
    public partial class getPurchasingDocumentUrl
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getPurchasingDocumentUrl()
        {
        }
        
        public getPurchasingDocumentUrl(string arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPurchasingDocumentUrlResponse", WrapperNamespace="purap", IsWrapped=true)]
    public partial class getPurchasingDocumentUrlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getPurchasingDocumentUrlResponse()
        {
        }
        
        public getPurchasingDocumentUrlResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface purchasingDocumentsInterfaceServiceSOAPChannel : Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class purchasingDocumentsInterfaceServiceSOAPClient : System.ServiceModel.ClientBase<Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP>, Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public purchasingDocumentsInterfaceServiceSOAPClient() : 
                base(purchasingDocumentsInterfaceServiceSOAPClient.GetDefaultBinding(), purchasingDocumentsInterfaceServiceSOAPClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.purchasingDocumentsInterfaceServiceSOAPPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public purchasingDocumentsInterfaceServiceSOAPClient(EndpointConfiguration endpointConfiguration) : 
                base(purchasingDocumentsInterfaceServiceSOAPClient.GetBindingForEndpoint(endpointConfiguration), purchasingDocumentsInterfaceServiceSOAPClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public purchasingDocumentsInterfaceServiceSOAPClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(purchasingDocumentsInterfaceServiceSOAPClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public purchasingDocumentsInterfaceServiceSOAPClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(purchasingDocumentsInterfaceServiceSOAPClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public purchasingDocumentsInterfaceServiceSOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatusResponse Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP.getPurchaseRequisitionStatus(Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatus request)
        {
            return base.Channel.getPurchaseRequisitionStatus(request);
        }
        
        public Purchasing.WS.PurchaseDocumentService.purchaseRequisitionStatusInfo getPurchaseRequisitionStatus(string arg0)
        {
            Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatus inValue = new Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatus();
            inValue.arg0 = arg0;
            Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatusResponse retVal = ((Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP)(this)).getPurchaseRequisitionStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatusResponse> Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP.getPurchaseRequisitionStatusAsync(Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatus request)
        {
            return base.Channel.getPurchaseRequisitionStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatusResponse> getPurchaseRequisitionStatusAsync(string arg0)
        {
            Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatus inValue = new Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatus();
            inValue.arg0 = arg0;
            return ((Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP)(this)).getPurchaseRequisitionStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Purchasing.WS.PurchaseDocumentService.uploadRequisitionResponse Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP.uploadRequisition(Purchasing.WS.PurchaseDocumentService.uploadRequisition request)
        {
            return base.Channel.uploadRequisition(request);
        }
        
        public Purchasing.WS.PurchaseDocumentService.documentCreationResult uploadRequisition(Purchasing.WS.PurchaseDocumentService.purchaseRequisitionInfo orderInfo, string securityToken, string feedOriginationCode)
        {
            Purchasing.WS.PurchaseDocumentService.uploadRequisition inValue = new Purchasing.WS.PurchaseDocumentService.uploadRequisition();
            inValue.orderInfo = orderInfo;
            inValue.securityToken = securityToken;
            inValue.feedOriginationCode = feedOriginationCode;
            Purchasing.WS.PurchaseDocumentService.uploadRequisitionResponse retVal = ((Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP)(this)).uploadRequisition(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Purchasing.WS.PurchaseDocumentService.uploadRequisitionResponse> Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP.uploadRequisitionAsync(Purchasing.WS.PurchaseDocumentService.uploadRequisition request)
        {
            return base.Channel.uploadRequisitionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Purchasing.WS.PurchaseDocumentService.uploadRequisitionResponse> uploadRequisitionAsync(Purchasing.WS.PurchaseDocumentService.purchaseRequisitionInfo orderInfo, string securityToken, string feedOriginationCode)
        {
            Purchasing.WS.PurchaseDocumentService.uploadRequisition inValue = new Purchasing.WS.PurchaseDocumentService.uploadRequisition();
            inValue.orderInfo = orderInfo;
            inValue.securityToken = securityToken;
            inValue.feedOriginationCode = feedOriginationCode;
            return ((Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP)(this)).uploadRequisitionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Purchasing.WS.PurchaseDocumentService.uploadRequisitionExtendResponse Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP.uploadRequisitionExtend(Purchasing.WS.PurchaseDocumentService.uploadRequisitionExtend request)
        {
            return base.Channel.uploadRequisitionExtend(request);
        }
        
        public Purchasing.WS.PurchaseDocumentService.documentCreationResult uploadRequisitionExtend(Purchasing.WS.PurchaseDocumentService.purchaseRequisitionInfo orderInfo, string securityToken, string feedOriginationCode)
        {
            Purchasing.WS.PurchaseDocumentService.uploadRequisitionExtend inValue = new Purchasing.WS.PurchaseDocumentService.uploadRequisitionExtend();
            inValue.orderInfo = orderInfo;
            inValue.securityToken = securityToken;
            inValue.feedOriginationCode = feedOriginationCode;
            Purchasing.WS.PurchaseDocumentService.uploadRequisitionExtendResponse retVal = ((Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP)(this)).uploadRequisitionExtend(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Purchasing.WS.PurchaseDocumentService.uploadRequisitionExtendResponse> Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP.uploadRequisitionExtendAsync(Purchasing.WS.PurchaseDocumentService.uploadRequisitionExtend request)
        {
            return base.Channel.uploadRequisitionExtendAsync(request);
        }
        
        public System.Threading.Tasks.Task<Purchasing.WS.PurchaseDocumentService.uploadRequisitionExtendResponse> uploadRequisitionExtendAsync(Purchasing.WS.PurchaseDocumentService.purchaseRequisitionInfo orderInfo, string securityToken, string feedOriginationCode)
        {
            Purchasing.WS.PurchaseDocumentService.uploadRequisitionExtend inValue = new Purchasing.WS.PurchaseDocumentService.uploadRequisitionExtend();
            inValue.orderInfo = orderInfo;
            inValue.securityToken = securityToken;
            inValue.feedOriginationCode = feedOriginationCode;
            return ((Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP)(this)).uploadRequisitionExtendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrlResponse Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP.getPurchasingDocumentUrl(Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrl request)
        {
            return base.Channel.getPurchasingDocumentUrl(request);
        }
        
        public string getPurchasingDocumentUrl(string arg0)
        {
            Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrl inValue = new Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrl();
            inValue.arg0 = arg0;
            Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrlResponse retVal = ((Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP)(this)).getPurchasingDocumentUrl(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrlResponse> Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP.getPurchasingDocumentUrlAsync(Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrl request)
        {
            return base.Channel.getPurchasingDocumentUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrlResponse> getPurchasingDocumentUrlAsync(string arg0)
        {
            Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrl inValue = new Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrl();
            inValue.arg0 = arg0;
            return ((Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP)(this)).getPurchasingDocumentUrlAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.purchasingDocumentsInterfaceServiceSOAPPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.purchasingDocumentsInterfaceServiceSOAPPort))
            {
                return new System.ServiceModel.EndpointAddress("http://kfs1.ucdavis.edu/kfs-prd/remoting/purchaseDocumentsInterfaceServiceSOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return purchasingDocumentsInterfaceServiceSOAPClient.GetBindingForEndpoint(EndpointConfiguration.purchasingDocumentsInterfaceServiceSOAPPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return purchasingDocumentsInterfaceServiceSOAPClient.GetEndpointAddress(EndpointConfiguration.purchasingDocumentsInterfaceServiceSOAPPort);
        }
        
        public enum EndpointConfiguration
        {
            
            purchasingDocumentsInterfaceServiceSOAPPort,
        }
    }
}
