//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchasing.WS.PurchaseDocumentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="purap", ConfigurationName="PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP")]
    public interface purchasingDocumentsInterfaceServiceSOAP {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatusResponse getPurchaseRequisitionStatus(Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatus request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Purchasing.WS.PurchaseDocumentService.uploadRequisitionResponse uploadRequisition(Purchasing.WS.PurchaseDocumentService.uploadRequisition request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrlResponse getPurchasingDocumentUrl(Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrl request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class purchaseRequisitionStatusInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentNumberField;
        
        private string documentUrlField;
        
        private bool fullyPaidField;
        
        private string purchaseOrderDocumentNumberField;
        
        private string purchaseOrderNumberField;
        
        private string purchaseOrderStatusCodeField;
        
        private string purchaseOrderStatusNameField;
        
        private string purchaseOrderTypeCodeField;
        
        private string purchaseRequsitionStatusCodeField;
        
        private string purchaseRequsitionStatusNameField;
        
        private bool receivedField;
        
        private string routeLevelField;
        
        private string routeStatusCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string documentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
                this.RaisePropertyChanged("documentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string documentUrl {
            get {
                return this.documentUrlField;
            }
            set {
                this.documentUrlField = value;
                this.RaisePropertyChanged("documentUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool fullyPaid {
            get {
                return this.fullyPaidField;
            }
            set {
                this.fullyPaidField = value;
                this.RaisePropertyChanged("fullyPaid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string purchaseOrderDocumentNumber {
            get {
                return this.purchaseOrderDocumentNumberField;
            }
            set {
                this.purchaseOrderDocumentNumberField = value;
                this.RaisePropertyChanged("purchaseOrderDocumentNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string purchaseOrderNumber {
            get {
                return this.purchaseOrderNumberField;
            }
            set {
                this.purchaseOrderNumberField = value;
                this.RaisePropertyChanged("purchaseOrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string purchaseOrderStatusCode {
            get {
                return this.purchaseOrderStatusCodeField;
            }
            set {
                this.purchaseOrderStatusCodeField = value;
                this.RaisePropertyChanged("purchaseOrderStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string purchaseOrderStatusName {
            get {
                return this.purchaseOrderStatusNameField;
            }
            set {
                this.purchaseOrderStatusNameField = value;
                this.RaisePropertyChanged("purchaseOrderStatusName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string purchaseOrderTypeCode {
            get {
                return this.purchaseOrderTypeCodeField;
            }
            set {
                this.purchaseOrderTypeCodeField = value;
                this.RaisePropertyChanged("purchaseOrderTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string purchaseRequsitionStatusCode {
            get {
                return this.purchaseRequsitionStatusCodeField;
            }
            set {
                this.purchaseRequsitionStatusCodeField = value;
                this.RaisePropertyChanged("purchaseRequsitionStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string purchaseRequsitionStatusName {
            get {
                return this.purchaseRequsitionStatusNameField;
            }
            set {
                this.purchaseRequsitionStatusNameField = value;
                this.RaisePropertyChanged("purchaseRequsitionStatusName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool received {
            get {
                return this.receivedField;
            }
            set {
                this.receivedField = value;
                this.RaisePropertyChanged("received");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string routeLevel {
            get {
                return this.routeLevelField;
            }
            set {
                this.routeLevelField = value;
                this.RaisePropertyChanged("routeLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string routeStatusCode {
            get {
                return this.routeStatusCodeField;
            }
            set {
                this.routeStatusCodeField = value;
                this.RaisePropertyChanged("routeStatusCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class resultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private string severityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("severity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class documentCreationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] documentNumbersField;
        
        private resultMessage[] messagesField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documentNumbers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] documentNumbers {
            get {
                return this.documentNumbersField;
            }
            set {
                this.documentNumbersField = value;
                this.RaisePropertyChanged("documentNumbers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("messages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public resultMessage[] messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
                this.RaisePropertyChanged("messages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class purchasingItemInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private purchasingAccountingInfo[] accountingLinesField;
        
        private string catelogNumberField;
        
        private string commodityCodeField;
        
        private string descriptionField;
        
        private string itemTypeCodeField;
        
        private string quantityField;
        
        private string unitOfMeasureCodeField;
        
        private string unitPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accountingLines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public purchasingAccountingInfo[] accountingLines {
            get {
                return this.accountingLinesField;
            }
            set {
                this.accountingLinesField = value;
                this.RaisePropertyChanged("accountingLines");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string catelogNumber {
            get {
                return this.catelogNumberField;
            }
            set {
                this.catelogNumberField = value;
                this.RaisePropertyChanged("catelogNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string commodityCode {
            get {
                return this.commodityCodeField;
            }
            set {
                this.commodityCodeField = value;
                this.RaisePropertyChanged("commodityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string itemTypeCode {
            get {
                return this.itemTypeCodeField;
            }
            set {
                this.itemTypeCodeField = value;
                this.RaisePropertyChanged("itemTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string unitOfMeasureCode {
            get {
                return this.unitOfMeasureCodeField;
            }
            set {
                this.unitOfMeasureCodeField = value;
                this.RaisePropertyChanged("unitOfMeasureCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string unitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
                this.RaisePropertyChanged("unitPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class purchasingAccountingInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNumberField;
        
        private string chartOfAccountsCodeField;
        
        private string distributionPercentField;
        
        private string objectCodeField;
        
        private string projectCodeField;
        
        private string subAccountNumberField;
        
        private string subObjectCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("accountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string chartOfAccountsCode {
            get {
                return this.chartOfAccountsCodeField;
            }
            set {
                this.chartOfAccountsCodeField = value;
                this.RaisePropertyChanged("chartOfAccountsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string distributionPercent {
            get {
                return this.distributionPercentField;
            }
            set {
                this.distributionPercentField = value;
                this.RaisePropertyChanged("distributionPercent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string objectCode {
            get {
                return this.objectCodeField;
            }
            set {
                this.objectCodeField = value;
                this.RaisePropertyChanged("objectCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string projectCode {
            get {
                return this.projectCodeField;
            }
            set {
                this.projectCodeField = value;
                this.RaisePropertyChanged("projectCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string subAccountNumber {
            get {
                return this.subAccountNumberField;
            }
            set {
                this.subAccountNumberField = value;
                this.RaisePropertyChanged("subAccountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string subObjectCode {
            get {
                return this.subObjectCodeField;
            }
            set {
                this.subObjectCodeField = value;
                this.RaisePropertyChanged("subObjectCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class documentInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string documentNoteField;
        
        private string explanationField;
        
        private string initiatorUserIdField;
        
        private string organizationTrackingNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string documentNote {
            get {
                return this.documentNoteField;
            }
            set {
                this.documentNoteField = value;
                this.RaisePropertyChanged("documentNote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string explanation {
            get {
                return this.explanationField;
            }
            set {
                this.explanationField = value;
                this.RaisePropertyChanged("explanation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string initiatorUserId {
            get {
                return this.initiatorUserIdField;
            }
            set {
                this.initiatorUserIdField = value;
                this.RaisePropertyChanged("initiatorUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string organizationTrackingNumber {
            get {
                return this.organizationTrackingNumberField;
            }
            set {
                this.organizationTrackingNumberField = value;
                this.RaisePropertyChanged("organizationTrackingNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class purchasingAddressInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string buildingCodeField;
        
        private string campusCodeField;
        
        private string cityNameField;
        
        private string countryCodeField;
        
        private string emailAddressField;
        
        private string nameField;
        
        private string phoneNumberField;
        
        private string roomNumberField;
        
        private string stateCodeField;
        
        private string zipCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string addressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
                this.RaisePropertyChanged("addressLine1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string addressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
                this.RaisePropertyChanged("addressLine2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string buildingCode {
            get {
                return this.buildingCodeField;
            }
            set {
                this.buildingCodeField = value;
                this.RaisePropertyChanged("buildingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string campusCode {
            get {
                return this.campusCodeField;
            }
            set {
                this.campusCodeField = value;
                this.RaisePropertyChanged("campusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
                this.RaisePropertyChanged("cityName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string emailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("emailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string roomNumber {
            get {
                return this.roomNumberField;
            }
            set {
                this.roomNumberField = value;
                this.RaisePropertyChanged("roomNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string stateCode {
            get {
                return this.stateCodeField;
            }
            set {
                this.stateCodeField = value;
                this.RaisePropertyChanged("stateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string zipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
                this.RaisePropertyChanged("zipCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="purap")]
    public partial class purchaseRequisitionInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string chartOfAccountsCodeField;
        
        private purchasingAddressInfo deliveryAddressField;
        
        private string deliveryInstructionTextField;
        
        private documentInfo documentInfoField;
        
        private purchasingAccountingInfo[] freightAccountingLinesField;
        
        private string freightAmountField;
        
        private purchasingItemInfo[] itemsField;
        
        private string organizationCodeField;
        
        private string priceSourceCodeField;
        
        private string requestTypeCodeField;
        
        private string requestorUserIdField;
        
        private string requiredDateField;
        
        private purchasingAccountingInfo[] shippingAndHandlingAccountingLinesField;
        
        private string shippingAndHandlingAmountField;
        
        private string shippingAndHandlingDescriptionField;
        
        private string sourceSystemOrderIdField;
        
        private string vendorAddressNumberField;
        
        private string vendorDetailIdField;
        
        private string vendorHeaderIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chartOfAccountsCode {
            get {
                return this.chartOfAccountsCodeField;
            }
            set {
                this.chartOfAccountsCodeField = value;
                this.RaisePropertyChanged("chartOfAccountsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public purchasingAddressInfo deliveryAddress {
            get {
                return this.deliveryAddressField;
            }
            set {
                this.deliveryAddressField = value;
                this.RaisePropertyChanged("deliveryAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string deliveryInstructionText {
            get {
                return this.deliveryInstructionTextField;
            }
            set {
                this.deliveryInstructionTextField = value;
                this.RaisePropertyChanged("deliveryInstructionText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public documentInfo documentInfo {
            get {
                return this.documentInfoField;
            }
            set {
                this.documentInfoField = value;
                this.RaisePropertyChanged("documentInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("freightAccountingLines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public purchasingAccountingInfo[] freightAccountingLines {
            get {
                return this.freightAccountingLinesField;
            }
            set {
                this.freightAccountingLinesField = value;
                this.RaisePropertyChanged("freightAccountingLines");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string freightAmount {
            get {
                return this.freightAmountField;
            }
            set {
                this.freightAmountField = value;
                this.RaisePropertyChanged("freightAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public purchasingItemInfo[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string organizationCode {
            get {
                return this.organizationCodeField;
            }
            set {
                this.organizationCodeField = value;
                this.RaisePropertyChanged("organizationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string priceSourceCode {
            get {
                return this.priceSourceCodeField;
            }
            set {
                this.priceSourceCodeField = value;
                this.RaisePropertyChanged("priceSourceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string requestTypeCode {
            get {
                return this.requestTypeCodeField;
            }
            set {
                this.requestTypeCodeField = value;
                this.RaisePropertyChanged("requestTypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string requestorUserId {
            get {
                return this.requestorUserIdField;
            }
            set {
                this.requestorUserIdField = value;
                this.RaisePropertyChanged("requestorUserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string requiredDate {
            get {
                return this.requiredDateField;
            }
            set {
                this.requiredDateField = value;
                this.RaisePropertyChanged("requiredDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("shippingAndHandlingAccountingLines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public purchasingAccountingInfo[] shippingAndHandlingAccountingLines {
            get {
                return this.shippingAndHandlingAccountingLinesField;
            }
            set {
                this.shippingAndHandlingAccountingLinesField = value;
                this.RaisePropertyChanged("shippingAndHandlingAccountingLines");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string shippingAndHandlingAmount {
            get {
                return this.shippingAndHandlingAmountField;
            }
            set {
                this.shippingAndHandlingAmountField = value;
                this.RaisePropertyChanged("shippingAndHandlingAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string shippingAndHandlingDescription {
            get {
                return this.shippingAndHandlingDescriptionField;
            }
            set {
                this.shippingAndHandlingDescriptionField = value;
                this.RaisePropertyChanged("shippingAndHandlingDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string sourceSystemOrderId {
            get {
                return this.sourceSystemOrderIdField;
            }
            set {
                this.sourceSystemOrderIdField = value;
                this.RaisePropertyChanged("sourceSystemOrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string vendorAddressNumber {
            get {
                return this.vendorAddressNumberField;
            }
            set {
                this.vendorAddressNumberField = value;
                this.RaisePropertyChanged("vendorAddressNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string vendorDetailId {
            get {
                return this.vendorDetailIdField;
            }
            set {
                this.vendorDetailIdField = value;
                this.RaisePropertyChanged("vendorDetailId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string vendorHeaderId {
            get {
                return this.vendorHeaderIdField;
            }
            set {
                this.vendorHeaderIdField = value;
                this.RaisePropertyChanged("vendorHeaderId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPurchaseRequisitionStatus", WrapperNamespace="purap", IsWrapped=true)]
    public partial class getPurchaseRequisitionStatus {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getPurchaseRequisitionStatus() {
        }
        
        public getPurchaseRequisitionStatus(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPurchaseRequisitionStatusResponse", WrapperNamespace="purap", IsWrapped=true)]
    public partial class getPurchaseRequisitionStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Purchasing.WS.PurchaseDocumentService.purchaseRequisitionStatusInfo @return;
        
        public getPurchaseRequisitionStatusResponse() {
        }
        
        public getPurchaseRequisitionStatusResponse(Purchasing.WS.PurchaseDocumentService.purchaseRequisitionStatusInfo @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadRequisition", WrapperNamespace="purap", IsWrapped=true)]
    public partial class uploadRequisition {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Purchasing.WS.PurchaseDocumentService.purchaseRequisitionInfo orderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string securityToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string feedOriginationCode;
        
        public uploadRequisition() {
        }
        
        public uploadRequisition(Purchasing.WS.PurchaseDocumentService.purchaseRequisitionInfo orderInfo, string securityToken, string feedOriginationCode) {
            this.orderInfo = orderInfo;
            this.securityToken = securityToken;
            this.feedOriginationCode = feedOriginationCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadRequisitionResponse", WrapperNamespace="purap", IsWrapped=true)]
    public partial class uploadRequisitionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Purchasing.WS.PurchaseDocumentService.documentCreationResult @return;
        
        public uploadRequisitionResponse() {
        }
        
        public uploadRequisitionResponse(Purchasing.WS.PurchaseDocumentService.documentCreationResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPurchasingDocumentUrl", WrapperNamespace="purap", IsWrapped=true)]
    public partial class getPurchasingDocumentUrl {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getPurchasingDocumentUrl() {
        }
        
        public getPurchasingDocumentUrl(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPurchasingDocumentUrlResponse", WrapperNamespace="purap", IsWrapped=true)]
    public partial class getPurchasingDocumentUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="purap", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getPurchasingDocumentUrlResponse() {
        }
        
        public getPurchasingDocumentUrlResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface purchasingDocumentsInterfaceServiceSOAPChannel : Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class purchasingDocumentsInterfaceServiceSOAPClient : System.ServiceModel.ClientBase<Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP>, Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP {
        
        public purchasingDocumentsInterfaceServiceSOAPClient() {
        }
        
        public purchasingDocumentsInterfaceServiceSOAPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public purchasingDocumentsInterfaceServiceSOAPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public purchasingDocumentsInterfaceServiceSOAPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public purchasingDocumentsInterfaceServiceSOAPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatusResponse Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP.getPurchaseRequisitionStatus(Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatus request) {
            return base.Channel.getPurchaseRequisitionStatus(request);
        }
        
        public Purchasing.WS.PurchaseDocumentService.purchaseRequisitionStatusInfo getPurchaseRequisitionStatus(string arg0) {
            Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatus inValue = new Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatus();
            inValue.arg0 = arg0;
            Purchasing.WS.PurchaseDocumentService.getPurchaseRequisitionStatusResponse retVal = ((Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP)(this)).getPurchaseRequisitionStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Purchasing.WS.PurchaseDocumentService.uploadRequisitionResponse Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP.uploadRequisition(Purchasing.WS.PurchaseDocumentService.uploadRequisition request) {
            return base.Channel.uploadRequisition(request);
        }
        
        public Purchasing.WS.PurchaseDocumentService.documentCreationResult uploadRequisition(Purchasing.WS.PurchaseDocumentService.purchaseRequisitionInfo orderInfo, string securityToken, string feedOriginationCode) {
            Purchasing.WS.PurchaseDocumentService.uploadRequisition inValue = new Purchasing.WS.PurchaseDocumentService.uploadRequisition();
            inValue.orderInfo = orderInfo;
            inValue.securityToken = securityToken;
            inValue.feedOriginationCode = feedOriginationCode;
            Purchasing.WS.PurchaseDocumentService.uploadRequisitionResponse retVal = ((Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP)(this)).uploadRequisition(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrlResponse Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP.getPurchasingDocumentUrl(Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrl request) {
            return base.Channel.getPurchasingDocumentUrl(request);
        }
        
        public string getPurchasingDocumentUrl(string arg0) {
            Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrl inValue = new Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrl();
            inValue.arg0 = arg0;
            Purchasing.WS.PurchaseDocumentService.getPurchasingDocumentUrlResponse retVal = ((Purchasing.WS.PurchaseDocumentService.purchasingDocumentsInterfaceServiceSOAP)(this)).getPurchasingDocumentUrl(inValue);
            return retVal.@return;
        }
    }
}
