//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchasing.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Purchasing.Web.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} action by {1} was not successful.
        /// </summary>
        public static string ApprovalAction_Fail {
            get {
                return ResourceManager.GetString("ApprovalAction_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} action for order #{1} processed successfully.
        /// </summary>
        public static string ApprovalAction_Success {
            get {
                return ResourceManager.GetString("ApprovalAction_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have the permissions required access this order.
        /// </summary>
        public static string Authorization_PermissionDenied {
            get {
                return ResourceManager.GetString("Authorization_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A comment is required when cancelling an order.
        /// </summary>
        public static string CancelOrder_CommentRequired {
            get {
                return ResourceManager.GetString("CancelOrder_CommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have access to cancel this order.
        /// </summary>
        public static string CancelOrder_NoAccess {
            get {
                return ResourceManager.GetString("CancelOrder_NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A comment is required when denying an order.
        /// </summary>
        public static string CommentRequired_Order {
            get {
                return ResourceManager.GetString("CommentRequired_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file provided to upload method.
        /// </summary>
        public static string FileUpload_NoFile {
            get {
                return ResourceManager.GetString("FileUpload_NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following account(s) can not be used because they are now inactive: .
        /// </summary>
        public static string InactiveAccounts_Warning {
            get {
                return ResourceManager.GetString("InactiveAccounts_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you were working on a form... do you want to load it back up?.
        /// </summary>
        public static string LocalStorage_LoadForm {
            get {
                return ResourceManager.GetString("LocalStorage_LoadForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order Created Successfully.
        /// </summary>
        public static string NewOrder_Success {
            get {
                return ResourceManager.GetString("NewOrder_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to the requested page.
        /// </summary>
        public static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to the PrePurchasing system.
        /// </summary>
        public static string NoAccess_Application {
            get {
                return ResourceManager.GetString("NoAccess_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to the requested Organization.
        /// </summary>
        public static string NoAccess_Org {
            get {
                return ResourceManager.GetString("NoAccess_Org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to create orders in this workgroup.
        /// </summary>
        public static string NoAccess_Workgroup {
            get {
                return ResourceManager.GetString("NoAccess_Workgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found..
        /// </summary>
        public static string NotFound_Order {
            get {
                return ResourceManager.GetString("NotFound_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the current line item split?.
        /// </summary>
        public static string Order_ConfirmCancelLineSplit {
            get {
                return ResourceManager.GetString("Order_ConfirmCancelLineSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the current order split?.
        /// </summary>
        public static string Order_ConfirmCancelOrderSplit {
            get {
                return ResourceManager.GetString("Order_ConfirmCancelOrderSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to split each line item across multiple accounts?.
        /// </summary>
        public static string Order_ConfirmLineSplit {
            get {
                return ResourceManager.GetString("Order_ConfirmLineSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling line item and account modification will necessitate recalculating approvals once this order edit is submitted..
        /// </summary>
        public static string Order_ConfirmModification {
            get {
                return ResourceManager.GetString("Order_ConfirmModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to split this order across multiple accounts?.
        /// </summary>
        public static string Order_ConfirmOrderSplit {
            get {
                return ResourceManager.GetString("Order_ConfirmOrderSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to save this order?.
        /// </summary>
        public static string Order_ConfirmSubmit {
            get {
                return ResourceManager.GetString("Order_ConfirmSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose either an account or an account manager to place this order as is.
        /// </summary>
        public static string Order_Error_AccountOrManagerRequired {
            get {
                return ResourceManager.GetString("Order_Error_AccountOrManagerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose an account to place this order as is.
        /// </summary>
        public static string Order_Error_AccountRequired {
            get {
                return ResourceManager.GetString("Order_Error_AccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Line item Detected.
        /// </summary>
        public static string Order_Error_LineItem {
            get {
                return ResourceManager.GetString("Order_Error_LineItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have at least one line item.
        /// </summary>
        public static string Order_Error_LineItemRequired {
            get {
                return ResourceManager.GetString("Order_Error_LineItemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a line item split with an amount but no account specified.
        /// </summary>
        public static string Order_Error_LineSplitNoAccount {
            get {
                return ResourceManager.GetString("Order_Error_LineSplitNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must account for the entire line item amount in each line item split.
        /// </summary>
        public static string Order_Error_LineSplitTotalAmountRequired {
            get {
                return ResourceManager.GetString("Order_Error_LineSplitTotalAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an order split with an amount but no account specified.
        /// </summary>
        public static string Order_Error_OrderSplitWithNoAccount {
            get {
                return ResourceManager.GetString("Order_Error_OrderSplitWithNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must account for the entire order amount.
        /// </summary>
        public static string Order_Error_TotalAmountRequired {
            get {
                return ResourceManager.GetString("Order_Error_TotalAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Commodity Codes Match.
        /// </summary>
        public static string Order_NoCommodityCodesMatch {
            get {
                return ResourceManager.GetString("Order_NoCommodityCodesMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        public static string Order_NoResults {
            get {
                return ResourceManager.GetString("Order_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Cancelled.
        /// </summary>
        public static string OrderCancelled_Success {
            get {
                return ResourceManager.GetString("OrderCancelled_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order Created: Existing Order Duplicated Successfully.
        /// </summary>
        public static string OrderCopy_Success {
            get {
                return ResourceManager.GetString("OrderCopy_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Edited!.
        /// </summary>
        public static string OrderEdit_Success {
            get {
                return ResourceManager.GetString("OrderEdit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FDP Completed updated.
        /// </summary>
        public static string OrderFdp_Updated {
            get {
                return ResourceManager.GetString("OrderFdp_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account needs to be outside of the workgroup..
        /// </summary>
        public static string ReRouteApproval_AccountError {
            get {
                return ResourceManager.GetString("ReRouteApproval_AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-Roles.
        /// </summary>
        public static string Role_CacheId {
            get {
                return ResourceManager.GetString("Role_CacheId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to view this file.
        /// </summary>
        public static string ViewFile_AccessDenied {
            get {
                return ResourceManager.GetString("ViewFile_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested file could not be found.
        /// </summary>
        public static string ViewFile_NotFound {
            get {
                return ResourceManager.GetString("ViewFile_NotFound", resourceCulture);
            }
        }
    }
}
