//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchasing.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Purchasing.Web.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} action by {1} processed successfully.
        /// </summary>
        public static string ApprovalAction_Success {
            get {
                return ResourceManager.GetString("ApprovalAction_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A comment is required when cancelling an order.
        /// </summary>
        public static string CancelOrder_CommentRequired {
            get {
                return ResourceManager.GetString("CancelOrder_CommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have access to cancel this order.
        /// </summary>
        public static string CancelOrder_NoAccess {
            get {
                return ResourceManager.GetString("CancelOrder_NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A comment is required when denying an order.
        /// </summary>
        public static string CommentRequired_Order {
            get {
                return ResourceManager.GetString("CommentRequired_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file provided to upload method.
        /// </summary>
        public static string FileUpload_NoFile {
            get {
                return ResourceManager.GetString("FileUpload_NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following account(s) can not be used because they are now inactive: .
        /// </summary>
        public static string InactiveAccounts_Warning {
            get {
                return ResourceManager.GetString("InactiveAccounts_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you were working on a form... do you want to load it back up?.
        /// </summary>
        public static string LocalStorage_LoadForm {
            get {
                return ResourceManager.GetString("LocalStorage_LoadForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order Created Successfully.
        /// </summary>
        public static string NewOrder_Success {
            get {
                return ResourceManager.GetString("NewOrder_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to create orders in this workgroup.
        /// </summary>
        public static string NoAccess_Workgroup {
            get {
                return ResourceManager.GetString("NoAccess_Workgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order not found..
        /// </summary>
        public static string NotFound_Order {
            get {
                return ResourceManager.GetString("NotFound_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Cancelled.
        /// </summary>
        public static string OrderCancelled_Success {
            get {
                return ResourceManager.GetString("OrderCancelled_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order Created: Existing Order Duplicated Successfully.
        /// </summary>
        public static string OrderCopy_Success {
            get {
                return ResourceManager.GetString("OrderCopy_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Edited!.
        /// </summary>
        public static string OrderEdit_Success {
            get {
                return ResourceManager.GetString("OrderEdit_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account needs to be outside of the workgroup..
        /// </summary>
        public static string ReRouteApproval_AccountError {
            get {
                return ResourceManager.GetString("ReRouteApproval_AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to view this file.
        /// </summary>
        public static string ViewFile_AccessDenied {
            get {
                return ResourceManager.GetString("ViewFile_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested file could not be found.
        /// </summary>
        public static string ViewFile_NotFound {
            get {
                return ResourceManager.GetString("ViewFile_NotFound", resourceCulture);
            }
        }
    }
}
