<?xml version="1.0" encoding="utf-8"?><Database Name="OVC_Dev" Class="ProfileDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ELK;Initial Catalog=OVC_Dev;Persist Security Info=True;User ID=web_aspnet" SettingsObjectName="OrAdmin.Entities.Properties.Settings" SettingsPropertyName="OVC_DevConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_Units" Member="Units">
    <Type Name="Unit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ChildOf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cluster" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UnitName" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="UnitAbbreviation" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="SubmittedOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SubmittedBy" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Comments" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Selectable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Unit_UserInUnit" Member="UserInUnits" ThisKey="Id" OtherKey="UnitId" Type="UserInUnit" />
      <Association Name="Unit_aspnet_AppProfile" Member="Profiles" ThisKey="Id" OtherKey="DefaultUnitId" Type="Profile" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_UsersInUnits" Member="UserInUnits">
    <Type Name="UserInUnit">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UnitId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrimaryUnit" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Unit_UserInUnit" Member="Unit" ThisKey="UnitId" OtherKey="Id" Type="Unit" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="User_UserInUnit" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="Users">
    <Type Name="User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_UserInUnit" Member="UserInUnits" ThisKey="UserId" OtherKey="UserId" Type="UserInUnit" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_AppProfiles" Member="Profiles">
    <Type Name="Profile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultUnitId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Unit_aspnet_AppProfile" Member="Unit" ThisKey="DefaultUnitId" OtherKey="Id" Type="Unit" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>